//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.2-hudson-jaxb-ri-2.2-63- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.12 at 06:01:42 PM PDT 
//


package com.intuit.sb.cdm.qbo.v2;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;


/**
 * <p>Java class for CdmCollections complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CdmCollections">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.intuit.com/sb/cdm/v2}CdmComplexBase">
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name = "CdmCollections", namespace = "http://www.intuit.com/sb/cdm/v2")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CdmCollections")
@XmlSeeAlso({
    BillPayments.class,
    Customers.class,
    Classes.class,
    Vendors.class,
    SalesReps.class,
    CreditCardCredits.class,
    CompaniesMetaData.class,
    Employees.class,
    VendorCredits.class,
    CashPurchases.class,
    Checks.class,
    SalesTerms.class,
    TimeActivities.class,
    Items.class,
    Discounts.class,
    ItemReceipts.class,
    InventoryAdjustments.class,
    Estimates.class,
    ShipMethods.class,
    SalesTaxPaymentChecks.class,
    CreditCardCharges.class,
    VendorCreditsToApply.class,
    SalesOrders.class,
    JournalEntries.class,
    Invoices.class,
    CreditMemos.class,
    TxnGenerics.class,
    SalesTaxCodes.class,
    UOMs.class,
    Payments.class,
    Bills.class,
    SalesReceipts.class,
    SalesTaxes.class,
    SalesTaxGroups.class,
    Jobs.class,
    Charges.class,
    PurchaseOrders.class,
    Accounts.class,
    PaymentMethods.class
})
public abstract class CdmCollections
    extends CdmComplexBase
    implements Serializable, Equals, HashCode
{

    private final static long serialVersionUID = 1L;

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof CdmCollections)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        if (!super.equals(thisLocator, thatLocator, object, strategy)) {
            return false;
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = super.hashCode(locator, strategy);
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
