//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.2-hudson-jaxb-ri-2.2-63- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.12 at 06:01:42 PM PDT 
//


package com.intuit.sb.cdm.qbo.v2;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Calendar;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * Superset of data that is associated with the Sale transaction types.
 * 
 * <p>Java class for HeaderSales complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HeaderSales">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.intuit.com/sb/cdm/v2}HeaderBase">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.intuit.com/sb/cdm/v2}CustomerReferenceGroup" minOccurs="0"/>
 *         &lt;group ref="{http://www.intuit.com/sb/cdm/v2}JobReferenceGroup" minOccurs="0"/>
 *         &lt;group ref="{http://www.intuit.com/sb/cdm/v2}RemitToReferenceGroup" minOccurs="0"/>
 *         &lt;group ref="{http://www.intuit.com/sb/cdm/v2}ClassReferenceGroup" minOccurs="0"/>
 *         &lt;group ref="{http://www.intuit.com/sb/cdm/v2}SalesRepReferenceGroup" minOccurs="0"/>
 *         &lt;group ref="{http://www.intuit.com/sb/cdm/v2}SalesTaxCodeReferenceGroup" minOccurs="0"/>
 *         &lt;element name="PONumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FOB" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ShipDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="SubTotalAmt" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;group ref="{http://www.intuit.com/sb/cdm/v2}TaxChoiceGroup" minOccurs="0"/>
 *         &lt;element name="TaxRate" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="TaxAmt" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="TotalAmt" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="ToBePrinted" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="ToBeEmailed" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="Custom" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HeaderSales", propOrder = {
    "customerId",
    "customerName",
    "jobId",
    "jobName",
    "remitToId",
    "remitToName",
    "classId",
    "className",
    "salesRepId",
    "salesRepName",
    "salesTaxCodeId",
    "salesTaxCodeName",
    "poNumber",
    "fob",
    "shipDate",
    "subTotalAmt",
    "taxId",
    "taxName",
    "taxGroupId",
    "taxGroupName",
    "taxRate",
    "taxAmt",
    "totalAmt",
    "toBePrinted",
    "toBeEmailed",
    "custom"
})
@XmlSeeAlso({
    SalesReceiptHeader.class,
    SalesOrderHeader.class,
    InvoiceHeader.class,
    CreditMemoHeader.class,
    EstimateHeader.class
})
public class HeaderSales
    extends HeaderBase
    implements Serializable, Equals, HashCode
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "CustomerId")
    protected IdType customerId;
    @XmlElement(name = "CustomerName")
    protected String customerName;
    @XmlElement(name = "JobId")
    protected IdType jobId;
    @XmlElement(name = "JobName")
    protected String jobName;
    @XmlElement(name = "RemitToId")
    protected IdType remitToId;
    @XmlElement(name = "RemitToName")
    protected String remitToName;
    @XmlElement(name = "ClassId")
    protected IdType classId;
    @XmlElement(name = "ClassName")
    protected String className;
    @XmlElement(name = "SalesRepId")
    protected IdType salesRepId;
    @XmlElement(name = "SalesRepName")
    protected String salesRepName;
    @XmlElement(name = "SalesTaxCodeId")
    protected IdType salesTaxCodeId;
    @XmlElement(name = "SalesTaxCodeName")
    protected String salesTaxCodeName;
    @XmlElement(name = "PONumber")
    protected String poNumber;
    @XmlElement(name = "FOB")
    protected String fob;
    @XmlElement(name = "ShipDate", type = String.class)
    @XmlJavaTypeAdapter(Adapter2 .class)
    @XmlSchemaType(name = "date")
    protected Calendar shipDate;
    @XmlElement(name = "SubTotalAmt")
    protected BigDecimal subTotalAmt;
    @XmlElement(name = "TaxId")
    protected IdType taxId;
    @XmlElement(name = "TaxName")
    protected String taxName;
    @XmlElement(name = "TaxGroupId")
    protected IdType taxGroupId;
    @XmlElement(name = "TaxGroupName")
    protected String taxGroupName;
    @XmlElement(name = "TaxRate")
    protected BigDecimal taxRate;
    @XmlElement(name = "TaxAmt")
    protected BigDecimal taxAmt;
    @XmlElement(name = "TotalAmt")
    protected BigDecimal totalAmt;
    @XmlElement(name = "ToBePrinted")
    protected Boolean toBePrinted;
    @XmlElement(name = "ToBeEmailed")
    protected Boolean toBeEmailed;
    @XmlElement(name = "Custom")
    protected String custom;

    /**
     * Gets the value of the customerId property.
     * 
     * @return
     *     possible object is
     *     {@link IdType }
     *     
     */
    public IdType getCustomerId() {
        return customerId;
    }

    /**
     * Sets the value of the customerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdType }
     *     
     */
    public void setCustomerId(IdType value) {
        this.customerId = value;
    }

    /**
     * Gets the value of the customerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * Sets the value of the customerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerName(String value) {
        this.customerName = value;
    }

    /**
     * Gets the value of the jobId property.
     * 
     * @return
     *     possible object is
     *     {@link IdType }
     *     
     */
    public IdType getJobId() {
        return jobId;
    }

    /**
     * Sets the value of the jobId property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdType }
     *     
     */
    public void setJobId(IdType value) {
        this.jobId = value;
    }

    /**
     * Gets the value of the jobName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * Sets the value of the jobName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJobName(String value) {
        this.jobName = value;
    }

    /**
     * Gets the value of the remitToId property.
     * 
     * @return
     *     possible object is
     *     {@link IdType }
     *     
     */
    public IdType getRemitToId() {
        return remitToId;
    }

    /**
     * Sets the value of the remitToId property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdType }
     *     
     */
    public void setRemitToId(IdType value) {
        this.remitToId = value;
    }

    /**
     * Gets the value of the remitToName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemitToName() {
        return remitToName;
    }

    /**
     * Sets the value of the remitToName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemitToName(String value) {
        this.remitToName = value;
    }

    /**
     * Gets the value of the classId property.
     * 
     * @return
     *     possible object is
     *     {@link IdType }
     *     
     */
    public IdType getClassId() {
        return classId;
    }

    /**
     * Sets the value of the classId property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdType }
     *     
     */
    public void setClassId(IdType value) {
        this.classId = value;
    }

    /**
     * Gets the value of the className property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassName() {
        return className;
    }

    /**
     * Sets the value of the className property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassName(String value) {
        this.className = value;
    }

    /**
     * Gets the value of the salesRepId property.
     * 
     * @return
     *     possible object is
     *     {@link IdType }
     *     
     */
    public IdType getSalesRepId() {
        return salesRepId;
    }

    /**
     * Sets the value of the salesRepId property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdType }
     *     
     */
    public void setSalesRepId(IdType value) {
        this.salesRepId = value;
    }

    /**
     * Gets the value of the salesRepName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSalesRepName() {
        return salesRepName;
    }

    /**
     * Sets the value of the salesRepName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSalesRepName(String value) {
        this.salesRepName = value;
    }

    /**
     * Gets the value of the salesTaxCodeId property.
     * 
     * @return
     *     possible object is
     *     {@link IdType }
     *     
     */
    public IdType getSalesTaxCodeId() {
        return salesTaxCodeId;
    }

    /**
     * Sets the value of the salesTaxCodeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdType }
     *     
     */
    public void setSalesTaxCodeId(IdType value) {
        this.salesTaxCodeId = value;
    }

    /**
     * Gets the value of the salesTaxCodeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSalesTaxCodeName() {
        return salesTaxCodeName;
    }

    /**
     * Sets the value of the salesTaxCodeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSalesTaxCodeName(String value) {
        this.salesTaxCodeName = value;
    }

    /**
     * Gets the value of the poNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPONumber() {
        return poNumber;
    }

    /**
     * Sets the value of the poNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPONumber(String value) {
        this.poNumber = value;
    }

    /**
     * Gets the value of the fob property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFOB() {
        return fob;
    }

    /**
     * Sets the value of the fob property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFOB(String value) {
        this.fob = value;
    }

    /**
     * Gets the value of the shipDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Calendar getShipDate() {
        return shipDate;
    }

    /**
     * Sets the value of the shipDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipDate(Calendar value) {
        this.shipDate = value;
    }

    /**
     * Gets the value of the subTotalAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSubTotalAmt() {
        return subTotalAmt;
    }

    /**
     * Sets the value of the subTotalAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSubTotalAmt(BigDecimal value) {
        this.subTotalAmt = value;
    }

    /**
     * Gets the value of the taxId property.
     * 
     * @return
     *     possible object is
     *     {@link IdType }
     *     
     */
    public IdType getTaxId() {
        return taxId;
    }

    /**
     * Sets the value of the taxId property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdType }
     *     
     */
    public void setTaxId(IdType value) {
        this.taxId = value;
    }

    /**
     * Gets the value of the taxName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxName() {
        return taxName;
    }

    /**
     * Sets the value of the taxName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxName(String value) {
        this.taxName = value;
    }

    /**
     * Gets the value of the taxGroupId property.
     * 
     * @return
     *     possible object is
     *     {@link IdType }
     *     
     */
    public IdType getTaxGroupId() {
        return taxGroupId;
    }

    /**
     * Sets the value of the taxGroupId property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdType }
     *     
     */
    public void setTaxGroupId(IdType value) {
        this.taxGroupId = value;
    }

    /**
     * Gets the value of the taxGroupName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxGroupName() {
        return taxGroupName;
    }

    /**
     * Sets the value of the taxGroupName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxGroupName(String value) {
        this.taxGroupName = value;
    }

    /**
     * Gets the value of the taxRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTaxRate() {
        return taxRate;
    }

    /**
     * Sets the value of the taxRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTaxRate(BigDecimal value) {
        this.taxRate = value;
    }

    /**
     * Gets the value of the taxAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTaxAmt() {
        return taxAmt;
    }

    /**
     * Sets the value of the taxAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTaxAmt(BigDecimal value) {
        this.taxAmt = value;
    }

    /**
     * Gets the value of the totalAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalAmt() {
        return totalAmt;
    }

    /**
     * Sets the value of the totalAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalAmt(BigDecimal value) {
        this.totalAmt = value;
    }

    /**
     * Gets the value of the toBePrinted property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isToBePrinted() {
        return toBePrinted;
    }

    /**
     * Sets the value of the toBePrinted property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setToBePrinted(Boolean value) {
        this.toBePrinted = value;
    }

    /**
     * Gets the value of the toBeEmailed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isToBeEmailed() {
        return toBeEmailed;
    }

    /**
     * Sets the value of the toBeEmailed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setToBeEmailed(Boolean value) {
        this.toBeEmailed = value;
    }

    /**
     * Gets the value of the custom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustom() {
        return custom;
    }

    /**
     * Sets the value of the custom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustom(String value) {
        this.custom = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof HeaderSales)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        if (!super.equals(thisLocator, thatLocator, object, strategy)) {
            return false;
        }
        final HeaderSales that = ((HeaderSales) object);
        {
            IdType lhsCustomerId;
            lhsCustomerId = this.getCustomerId();
            IdType rhsCustomerId;
            rhsCustomerId = that.getCustomerId();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "customerId", lhsCustomerId), LocatorUtils.property(thatLocator, "customerId", rhsCustomerId), lhsCustomerId, rhsCustomerId)) {
                return false;
            }
        }
        {
            String lhsCustomerName;
            lhsCustomerName = this.getCustomerName();
            String rhsCustomerName;
            rhsCustomerName = that.getCustomerName();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "customerName", lhsCustomerName), LocatorUtils.property(thatLocator, "customerName", rhsCustomerName), lhsCustomerName, rhsCustomerName)) {
                return false;
            }
        }
        {
            IdType lhsJobId;
            lhsJobId = this.getJobId();
            IdType rhsJobId;
            rhsJobId = that.getJobId();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "jobId", lhsJobId), LocatorUtils.property(thatLocator, "jobId", rhsJobId), lhsJobId, rhsJobId)) {
                return false;
            }
        }
        {
            String lhsJobName;
            lhsJobName = this.getJobName();
            String rhsJobName;
            rhsJobName = that.getJobName();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "jobName", lhsJobName), LocatorUtils.property(thatLocator, "jobName", rhsJobName), lhsJobName, rhsJobName)) {
                return false;
            }
        }
        {
            IdType lhsRemitToId;
            lhsRemitToId = this.getRemitToId();
            IdType rhsRemitToId;
            rhsRemitToId = that.getRemitToId();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "remitToId", lhsRemitToId), LocatorUtils.property(thatLocator, "remitToId", rhsRemitToId), lhsRemitToId, rhsRemitToId)) {
                return false;
            }
        }
        {
            String lhsRemitToName;
            lhsRemitToName = this.getRemitToName();
            String rhsRemitToName;
            rhsRemitToName = that.getRemitToName();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "remitToName", lhsRemitToName), LocatorUtils.property(thatLocator, "remitToName", rhsRemitToName), lhsRemitToName, rhsRemitToName)) {
                return false;
            }
        }
        {
            IdType lhsClassId;
            lhsClassId = this.getClassId();
            IdType rhsClassId;
            rhsClassId = that.getClassId();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "classId", lhsClassId), LocatorUtils.property(thatLocator, "classId", rhsClassId), lhsClassId, rhsClassId)) {
                return false;
            }
        }
        {
            String lhsClassName;
            lhsClassName = this.getClassName();
            String rhsClassName;
            rhsClassName = that.getClassName();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "className", lhsClassName), LocatorUtils.property(thatLocator, "className", rhsClassName), lhsClassName, rhsClassName)) {
                return false;
            }
        }
        {
            IdType lhsSalesRepId;
            lhsSalesRepId = this.getSalesRepId();
            IdType rhsSalesRepId;
            rhsSalesRepId = that.getSalesRepId();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "salesRepId", lhsSalesRepId), LocatorUtils.property(thatLocator, "salesRepId", rhsSalesRepId), lhsSalesRepId, rhsSalesRepId)) {
                return false;
            }
        }
        {
            String lhsSalesRepName;
            lhsSalesRepName = this.getSalesRepName();
            String rhsSalesRepName;
            rhsSalesRepName = that.getSalesRepName();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "salesRepName", lhsSalesRepName), LocatorUtils.property(thatLocator, "salesRepName", rhsSalesRepName), lhsSalesRepName, rhsSalesRepName)) {
                return false;
            }
        }
        {
            IdType lhsSalesTaxCodeId;
            lhsSalesTaxCodeId = this.getSalesTaxCodeId();
            IdType rhsSalesTaxCodeId;
            rhsSalesTaxCodeId = that.getSalesTaxCodeId();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "salesTaxCodeId", lhsSalesTaxCodeId), LocatorUtils.property(thatLocator, "salesTaxCodeId", rhsSalesTaxCodeId), lhsSalesTaxCodeId, rhsSalesTaxCodeId)) {
                return false;
            }
        }
        {
            String lhsSalesTaxCodeName;
            lhsSalesTaxCodeName = this.getSalesTaxCodeName();
            String rhsSalesTaxCodeName;
            rhsSalesTaxCodeName = that.getSalesTaxCodeName();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "salesTaxCodeName", lhsSalesTaxCodeName), LocatorUtils.property(thatLocator, "salesTaxCodeName", rhsSalesTaxCodeName), lhsSalesTaxCodeName, rhsSalesTaxCodeName)) {
                return false;
            }
        }
        {
            String lhsPONumber;
            lhsPONumber = this.getPONumber();
            String rhsPONumber;
            rhsPONumber = that.getPONumber();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "poNumber", lhsPONumber), LocatorUtils.property(thatLocator, "poNumber", rhsPONumber), lhsPONumber, rhsPONumber)) {
                return false;
            }
        }
        {
            String lhsFOB;
            lhsFOB = this.getFOB();
            String rhsFOB;
            rhsFOB = that.getFOB();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "fob", lhsFOB), LocatorUtils.property(thatLocator, "fob", rhsFOB), lhsFOB, rhsFOB)) {
                return false;
            }
        }
        {
            Calendar lhsShipDate;
            lhsShipDate = this.getShipDate();
            Calendar rhsShipDate;
            rhsShipDate = that.getShipDate();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "shipDate", lhsShipDate), LocatorUtils.property(thatLocator, "shipDate", rhsShipDate), lhsShipDate, rhsShipDate)) {
                return false;
            }
        }
        {
            BigDecimal lhsSubTotalAmt;
            lhsSubTotalAmt = this.getSubTotalAmt();
            BigDecimal rhsSubTotalAmt;
            rhsSubTotalAmt = that.getSubTotalAmt();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "subTotalAmt", lhsSubTotalAmt), LocatorUtils.property(thatLocator, "subTotalAmt", rhsSubTotalAmt), lhsSubTotalAmt, rhsSubTotalAmt)) {
                return false;
            }
        }
        {
            IdType lhsTaxId;
            lhsTaxId = this.getTaxId();
            IdType rhsTaxId;
            rhsTaxId = that.getTaxId();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "taxId", lhsTaxId), LocatorUtils.property(thatLocator, "taxId", rhsTaxId), lhsTaxId, rhsTaxId)) {
                return false;
            }
        }
        {
            String lhsTaxName;
            lhsTaxName = this.getTaxName();
            String rhsTaxName;
            rhsTaxName = that.getTaxName();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "taxName", lhsTaxName), LocatorUtils.property(thatLocator, "taxName", rhsTaxName), lhsTaxName, rhsTaxName)) {
                return false;
            }
        }
        {
            IdType lhsTaxGroupId;
            lhsTaxGroupId = this.getTaxGroupId();
            IdType rhsTaxGroupId;
            rhsTaxGroupId = that.getTaxGroupId();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "taxGroupId", lhsTaxGroupId), LocatorUtils.property(thatLocator, "taxGroupId", rhsTaxGroupId), lhsTaxGroupId, rhsTaxGroupId)) {
                return false;
            }
        }
        {
            String lhsTaxGroupName;
            lhsTaxGroupName = this.getTaxGroupName();
            String rhsTaxGroupName;
            rhsTaxGroupName = that.getTaxGroupName();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "taxGroupName", lhsTaxGroupName), LocatorUtils.property(thatLocator, "taxGroupName", rhsTaxGroupName), lhsTaxGroupName, rhsTaxGroupName)) {
                return false;
            }
        }
        {
            BigDecimal lhsTaxRate;
            lhsTaxRate = this.getTaxRate();
            BigDecimal rhsTaxRate;
            rhsTaxRate = that.getTaxRate();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "taxRate", lhsTaxRate), LocatorUtils.property(thatLocator, "taxRate", rhsTaxRate), lhsTaxRate, rhsTaxRate)) {
                return false;
            }
        }
        {
            BigDecimal lhsTaxAmt;
            lhsTaxAmt = this.getTaxAmt();
            BigDecimal rhsTaxAmt;
            rhsTaxAmt = that.getTaxAmt();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "taxAmt", lhsTaxAmt), LocatorUtils.property(thatLocator, "taxAmt", rhsTaxAmt), lhsTaxAmt, rhsTaxAmt)) {
                return false;
            }
        }
        {
            BigDecimal lhsTotalAmt;
            lhsTotalAmt = this.getTotalAmt();
            BigDecimal rhsTotalAmt;
            rhsTotalAmt = that.getTotalAmt();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "totalAmt", lhsTotalAmt), LocatorUtils.property(thatLocator, "totalAmt", rhsTotalAmt), lhsTotalAmt, rhsTotalAmt)) {
                return false;
            }
        }
        {
            Boolean lhsToBePrinted;
            lhsToBePrinted = this.isToBePrinted();
            Boolean rhsToBePrinted;
            rhsToBePrinted = that.isToBePrinted();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "toBePrinted", lhsToBePrinted), LocatorUtils.property(thatLocator, "toBePrinted", rhsToBePrinted), lhsToBePrinted, rhsToBePrinted)) {
                return false;
            }
        }
        {
            Boolean lhsToBeEmailed;
            lhsToBeEmailed = this.isToBeEmailed();
            Boolean rhsToBeEmailed;
            rhsToBeEmailed = that.isToBeEmailed();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "toBeEmailed", lhsToBeEmailed), LocatorUtils.property(thatLocator, "toBeEmailed", rhsToBeEmailed), lhsToBeEmailed, rhsToBeEmailed)) {
                return false;
            }
        }
        {
            String lhsCustom;
            lhsCustom = this.getCustom();
            String rhsCustom;
            rhsCustom = that.getCustom();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "custom", lhsCustom), LocatorUtils.property(thatLocator, "custom", rhsCustom), lhsCustom, rhsCustom)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = super.hashCode(locator, strategy);
        {
            IdType theCustomerId;
            theCustomerId = this.getCustomerId();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "customerId", theCustomerId), currentHashCode, theCustomerId);
        }
        {
            String theCustomerName;
            theCustomerName = this.getCustomerName();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "customerName", theCustomerName), currentHashCode, theCustomerName);
        }
        {
            IdType theJobId;
            theJobId = this.getJobId();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "jobId", theJobId), currentHashCode, theJobId);
        }
        {
            String theJobName;
            theJobName = this.getJobName();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "jobName", theJobName), currentHashCode, theJobName);
        }
        {
            IdType theRemitToId;
            theRemitToId = this.getRemitToId();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "remitToId", theRemitToId), currentHashCode, theRemitToId);
        }
        {
            String theRemitToName;
            theRemitToName = this.getRemitToName();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "remitToName", theRemitToName), currentHashCode, theRemitToName);
        }
        {
            IdType theClassId;
            theClassId = this.getClassId();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "classId", theClassId), currentHashCode, theClassId);
        }
        {
            String theClassName;
            theClassName = this.getClassName();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "className", theClassName), currentHashCode, theClassName);
        }
        {
            IdType theSalesRepId;
            theSalesRepId = this.getSalesRepId();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "salesRepId", theSalesRepId), currentHashCode, theSalesRepId);
        }
        {
            String theSalesRepName;
            theSalesRepName = this.getSalesRepName();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "salesRepName", theSalesRepName), currentHashCode, theSalesRepName);
        }
        {
            IdType theSalesTaxCodeId;
            theSalesTaxCodeId = this.getSalesTaxCodeId();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "salesTaxCodeId", theSalesTaxCodeId), currentHashCode, theSalesTaxCodeId);
        }
        {
            String theSalesTaxCodeName;
            theSalesTaxCodeName = this.getSalesTaxCodeName();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "salesTaxCodeName", theSalesTaxCodeName), currentHashCode, theSalesTaxCodeName);
        }
        {
            String thePONumber;
            thePONumber = this.getPONumber();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "poNumber", thePONumber), currentHashCode, thePONumber);
        }
        {
            String theFOB;
            theFOB = this.getFOB();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "fob", theFOB), currentHashCode, theFOB);
        }
        {
            Calendar theShipDate;
            theShipDate = this.getShipDate();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "shipDate", theShipDate), currentHashCode, theShipDate);
        }
        {
            BigDecimal theSubTotalAmt;
            theSubTotalAmt = this.getSubTotalAmt();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "subTotalAmt", theSubTotalAmt), currentHashCode, theSubTotalAmt);
        }
        {
            IdType theTaxId;
            theTaxId = this.getTaxId();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "taxId", theTaxId), currentHashCode, theTaxId);
        }
        {
            String theTaxName;
            theTaxName = this.getTaxName();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "taxName", theTaxName), currentHashCode, theTaxName);
        }
        {
            IdType theTaxGroupId;
            theTaxGroupId = this.getTaxGroupId();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "taxGroupId", theTaxGroupId), currentHashCode, theTaxGroupId);
        }
        {
            String theTaxGroupName;
            theTaxGroupName = this.getTaxGroupName();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "taxGroupName", theTaxGroupName), currentHashCode, theTaxGroupName);
        }
        {
            BigDecimal theTaxRate;
            theTaxRate = this.getTaxRate();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "taxRate", theTaxRate), currentHashCode, theTaxRate);
        }
        {
            BigDecimal theTaxAmt;
            theTaxAmt = this.getTaxAmt();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "taxAmt", theTaxAmt), currentHashCode, theTaxAmt);
        }
        {
            BigDecimal theTotalAmt;
            theTotalAmt = this.getTotalAmt();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "totalAmt", theTotalAmt), currentHashCode, theTotalAmt);
        }
        {
            Boolean theToBePrinted;
            theToBePrinted = this.isToBePrinted();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "toBePrinted", theToBePrinted), currentHashCode, theToBePrinted);
        }
        {
            Boolean theToBeEmailed;
            theToBeEmailed = this.isToBeEmailed();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "toBeEmailed", theToBeEmailed), currentHashCode, theToBeEmailed);
        }
        {
            String theCustom;
            theCustom = this.getCustom();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "custom", theCustom), currentHashCode, theCustom);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
