//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.2-hudson-jaxb-ri-2.2-63- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.12 at 06:01:42 PM PDT 
//


package com.intuit.sb.cdm.qbo.v2;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * Financial Transaction information that pertains to the entire ItemReceipt.
 * 
 * <p>Java class for ItemReceiptHeader complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ItemReceiptHeader">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.intuit.com/sb/cdm/v2}HeaderPurchase">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.intuit.com/sb/cdm/v2}APAccountReferenceGroup" minOccurs="0"/>
 *         &lt;element name="TxnId" type="{http://www.intuit.com/sb/cdm/v2}IdType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ItemReceiptHeader", propOrder = {
    "apAccountId",
    "apAccountName",
    "txnId"
})
public class ItemReceiptHeader
    extends HeaderPurchase
    implements Serializable, Equals, HashCode
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "APAccountId")
    protected IdType apAccountId;
    @XmlElement(name = "APAccountName")
    protected String apAccountName;
    @XmlElement(name = "TxnId")
    protected List<IdType> txnId;

    /**
     * Gets the value of the apAccountId property.
     * 
     * @return
     *     possible object is
     *     {@link IdType }
     *     
     */
    public IdType getAPAccountId() {
        return apAccountId;
    }

    /**
     * Sets the value of the apAccountId property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdType }
     *     
     */
    public void setAPAccountId(IdType value) {
        this.apAccountId = value;
    }

    /**
     * Gets the value of the apAccountName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAPAccountName() {
        return apAccountName;
    }

    /**
     * Sets the value of the apAccountName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAPAccountName(String value) {
        this.apAccountName = value;
    }

    /**
     * Gets the value of the txnId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the txnId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTxnId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IdType }
     * 
     * 
     */
    public List<IdType> getTxnId() {
        if (txnId == null) {
            txnId = new ArrayList<IdType>();
        }
        return this.txnId;
    }

    /**
     * Sets the value of the txnId property.
     * 
     * @param txnId
     *     allowed object is
     *     {@link IdType }
     *     
     */
    public void setTxnId(List<IdType> txnId) {
        this.txnId = txnId;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof ItemReceiptHeader)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        if (!super.equals(thisLocator, thatLocator, object, strategy)) {
            return false;
        }
        final ItemReceiptHeader that = ((ItemReceiptHeader) object);
        {
            IdType lhsAPAccountId;
            lhsAPAccountId = this.getAPAccountId();
            IdType rhsAPAccountId;
            rhsAPAccountId = that.getAPAccountId();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "apAccountId", lhsAPAccountId), LocatorUtils.property(thatLocator, "apAccountId", rhsAPAccountId), lhsAPAccountId, rhsAPAccountId)) {
                return false;
            }
        }
        {
            String lhsAPAccountName;
            lhsAPAccountName = this.getAPAccountName();
            String rhsAPAccountName;
            rhsAPAccountName = that.getAPAccountName();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "apAccountName", lhsAPAccountName), LocatorUtils.property(thatLocator, "apAccountName", rhsAPAccountName), lhsAPAccountName, rhsAPAccountName)) {
                return false;
            }
        }
        {
            List<IdType> lhsTxnId;
            lhsTxnId = this.getTxnId();
            List<IdType> rhsTxnId;
            rhsTxnId = that.getTxnId();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "txnId", lhsTxnId), LocatorUtils.property(thatLocator, "txnId", rhsTxnId), lhsTxnId, rhsTxnId)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = super.hashCode(locator, strategy);
        {
            IdType theAPAccountId;
            theAPAccountId = this.getAPAccountId();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "apAccountId", theAPAccountId), currentHashCode, theAPAccountId);
        }
        {
            String theAPAccountName;
            theAPAccountName = this.getAPAccountName();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "apAccountName", theAPAccountName), currentHashCode, theAPAccountName);
        }
        {
            List<IdType> theTxnId;
            theTxnId = this.getTxnId();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "txnId", theTxnId), currentHashCode, theTxnId);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
