//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.2-hudson-jaxb-ri-2.2-63- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.12 at 06:01:42 PM PDT 
//


package com.intuit.sb.cdm.qbo.v2;

import java.io.Serializable;
import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * Information associating some portion of the payment with a sales transaction that is paid by it.
 * 
 * <p>Java class for PaymentLine complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PaymentLine">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.intuit.com/sb/cdm/v2}LineBase">
 *       &lt;sequence>
 *         &lt;element name="Amount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;group ref="{http://www.intuit.com/sb/cdm/v2}TxnReferenceGroup" minOccurs="0"/>
 *         &lt;element name="DiscountAmt" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;group ref="{http://www.intuit.com/sb/cdm/v2}DiscountReferenceGroup" minOccurs="0"/>
 *         &lt;group ref="{http://www.intuit.com/sb/cdm/v2}DiscountAccountReferenceGroup" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PaymentLine", propOrder = {
    "amount",
    "txnId",
    "txnNum",
    "discountAmt",
    "discountId",
    "discountName",
    "discountAccountId",
    "discountAccountName"
})
public class PaymentLine
    extends LineBase
    implements Serializable, Equals, HashCode
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "Amount")
    protected BigDecimal amount;
    @XmlElement(name = "TxnId")
    protected IdType txnId;
    @XmlElement(name = "TxnNum")
    protected String txnNum;
    @XmlElement(name = "DiscountAmt")
    protected BigDecimal discountAmt;
    @XmlElement(name = "DiscountId")
    protected IdType discountId;
    @XmlElement(name = "DiscountName")
    protected String discountName;
    @XmlElement(name = "DiscountAccountId")
    protected IdType discountAccountId;
    @XmlElement(name = "DiscountAccountName")
    protected String discountAccountName;

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAmount(BigDecimal value) {
        this.amount = value;
    }

    /**
     * Gets the value of the txnId property.
     * 
     * @return
     *     possible object is
     *     {@link IdType }
     *     
     */
    public IdType getTxnId() {
        return txnId;
    }

    /**
     * Sets the value of the txnId property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdType }
     *     
     */
    public void setTxnId(IdType value) {
        this.txnId = value;
    }

    /**
     * Gets the value of the txnNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxnNum() {
        return txnNum;
    }

    /**
     * Sets the value of the txnNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxnNum(String value) {
        this.txnNum = value;
    }

    /**
     * Gets the value of the discountAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDiscountAmt() {
        return discountAmt;
    }

    /**
     * Sets the value of the discountAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDiscountAmt(BigDecimal value) {
        this.discountAmt = value;
    }

    /**
     * Gets the value of the discountId property.
     * 
     * @return
     *     possible object is
     *     {@link IdType }
     *     
     */
    public IdType getDiscountId() {
        return discountId;
    }

    /**
     * Sets the value of the discountId property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdType }
     *     
     */
    public void setDiscountId(IdType value) {
        this.discountId = value;
    }

    /**
     * Gets the value of the discountName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiscountName() {
        return discountName;
    }

    /**
     * Sets the value of the discountName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiscountName(String value) {
        this.discountName = value;
    }

    /**
     * Gets the value of the discountAccountId property.
     * 
     * @return
     *     possible object is
     *     {@link IdType }
     *     
     */
    public IdType getDiscountAccountId() {
        return discountAccountId;
    }

    /**
     * Sets the value of the discountAccountId property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdType }
     *     
     */
    public void setDiscountAccountId(IdType value) {
        this.discountAccountId = value;
    }

    /**
     * Gets the value of the discountAccountName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiscountAccountName() {
        return discountAccountName;
    }

    /**
     * Sets the value of the discountAccountName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiscountAccountName(String value) {
        this.discountAccountName = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof PaymentLine)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        if (!super.equals(thisLocator, thatLocator, object, strategy)) {
            return false;
        }
        final PaymentLine that = ((PaymentLine) object);
        {
            BigDecimal lhsAmount;
            lhsAmount = this.getAmount();
            BigDecimal rhsAmount;
            rhsAmount = that.getAmount();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "amount", lhsAmount), LocatorUtils.property(thatLocator, "amount", rhsAmount), lhsAmount, rhsAmount)) {
                return false;
            }
        }
        {
            IdType lhsTxnId;
            lhsTxnId = this.getTxnId();
            IdType rhsTxnId;
            rhsTxnId = that.getTxnId();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "txnId", lhsTxnId), LocatorUtils.property(thatLocator, "txnId", rhsTxnId), lhsTxnId, rhsTxnId)) {
                return false;
            }
        }
        {
            String lhsTxnNum;
            lhsTxnNum = this.getTxnNum();
            String rhsTxnNum;
            rhsTxnNum = that.getTxnNum();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "txnNum", lhsTxnNum), LocatorUtils.property(thatLocator, "txnNum", rhsTxnNum), lhsTxnNum, rhsTxnNum)) {
                return false;
            }
        }
        {
            BigDecimal lhsDiscountAmt;
            lhsDiscountAmt = this.getDiscountAmt();
            BigDecimal rhsDiscountAmt;
            rhsDiscountAmt = that.getDiscountAmt();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "discountAmt", lhsDiscountAmt), LocatorUtils.property(thatLocator, "discountAmt", rhsDiscountAmt), lhsDiscountAmt, rhsDiscountAmt)) {
                return false;
            }
        }
        {
            IdType lhsDiscountId;
            lhsDiscountId = this.getDiscountId();
            IdType rhsDiscountId;
            rhsDiscountId = that.getDiscountId();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "discountId", lhsDiscountId), LocatorUtils.property(thatLocator, "discountId", rhsDiscountId), lhsDiscountId, rhsDiscountId)) {
                return false;
            }
        }
        {
            String lhsDiscountName;
            lhsDiscountName = this.getDiscountName();
            String rhsDiscountName;
            rhsDiscountName = that.getDiscountName();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "discountName", lhsDiscountName), LocatorUtils.property(thatLocator, "discountName", rhsDiscountName), lhsDiscountName, rhsDiscountName)) {
                return false;
            }
        }
        {
            IdType lhsDiscountAccountId;
            lhsDiscountAccountId = this.getDiscountAccountId();
            IdType rhsDiscountAccountId;
            rhsDiscountAccountId = that.getDiscountAccountId();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "discountAccountId", lhsDiscountAccountId), LocatorUtils.property(thatLocator, "discountAccountId", rhsDiscountAccountId), lhsDiscountAccountId, rhsDiscountAccountId)) {
                return false;
            }
        }
        {
            String lhsDiscountAccountName;
            lhsDiscountAccountName = this.getDiscountAccountName();
            String rhsDiscountAccountName;
            rhsDiscountAccountName = that.getDiscountAccountName();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "discountAccountName", lhsDiscountAccountName), LocatorUtils.property(thatLocator, "discountAccountName", rhsDiscountAccountName), lhsDiscountAccountName, rhsDiscountAccountName)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = super.hashCode(locator, strategy);
        {
            BigDecimal theAmount;
            theAmount = this.getAmount();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "amount", theAmount), currentHashCode, theAmount);
        }
        {
            IdType theTxnId;
            theTxnId = this.getTxnId();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "txnId", theTxnId), currentHashCode, theTxnId);
        }
        {
            String theTxnNum;
            theTxnNum = this.getTxnNum();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "txnNum", theTxnNum), currentHashCode, theTxnNum);
        }
        {
            BigDecimal theDiscountAmt;
            theDiscountAmt = this.getDiscountAmt();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "discountAmt", theDiscountAmt), currentHashCode, theDiscountAmt);
        }
        {
            IdType theDiscountId;
            theDiscountId = this.getDiscountId();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "discountId", theDiscountId), currentHashCode, theDiscountId);
        }
        {
            String theDiscountName;
            theDiscountName = this.getDiscountName();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "discountName", theDiscountName), currentHashCode, theDiscountName);
        }
        {
            IdType theDiscountAccountId;
            theDiscountAccountId = this.getDiscountAccountId();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "discountAccountId", theDiscountAccountId), currentHashCode, theDiscountAccountId);
        }
        {
            String theDiscountAccountName;
            theDiscountAccountName = this.getDiscountAccountName();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "discountAccountName", theDiscountAccountName), currentHashCode, theDiscountAccountName);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
