//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.2-hudson-jaxb-ri-2.2-63- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.12 at 06:01:41 PM PDT 
//


package com.intuit.sb.cdm.qbo.v2;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * Used to output a balance sheet report. These default fields are set by QBO and filled in
 *             by the reporting engine. 
 * 
 * <p>Java class for QboBalanceSheetReportResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QboBalanceSheetReportResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Assets">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CurrentAssets">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="BankAccounts" type="{http://www.intuit.com/sb/cdm/qboReports}ReportAccount" maxOccurs="unbounded" minOccurs="0"/>
 *                             &lt;element name="TotalBankAccounts" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="AccountsReceivable" type="{http://www.intuit.com/sb/cdm/qboReports}ReportAccount" maxOccurs="unbounded" minOccurs="0"/>
 *                             &lt;element name="TotalAccountsReceivable" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="OtherCurrentAssets" type="{http://www.intuit.com/sb/cdm/qboReports}ReportAccount" maxOccurs="unbounded" minOccurs="0"/>
 *                             &lt;element name="TotalOtherCurrentAssets" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="TotalCurrentAssets" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="FixedAssets" type="{http://www.intuit.com/sb/cdm/qboReports}ReportAccount" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="TotalFixedAssets" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="OtherAssets" type="{http://www.intuit.com/sb/cdm/qboReports}ReportAccount" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="TotalOtherAssets" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="TotalAssets" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LiabilitiesAndEquity">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Liabilities">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="CurrentLiabilities">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="AccountsPayable" type="{http://www.intuit.com/sb/cdm/qboReports}ReportAccount" maxOccurs="unbounded" minOccurs="0"/>
 *                                       &lt;element name="TotalAccountsPayable" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="CreditCards" type="{http://www.intuit.com/sb/cdm/qboReports}ReportAccount" maxOccurs="unbounded" minOccurs="0"/>
 *                                       &lt;element name="TotalCreditCards" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="OtherCurrentLiabilities" type="{http://www.intuit.com/sb/cdm/qboReports}ReportAccount" maxOccurs="unbounded" minOccurs="0"/>
 *                                       &lt;element name="TotalOtherCurrentLiabilities" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="TotalCurrentLiabilities" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="LongTermLiabilities" type="{http://www.intuit.com/sb/cdm/qboReports}ReportAccount" maxOccurs="unbounded" minOccurs="0"/>
 *                             &lt;element name="TotalLongTermLiabilities" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="TotalLiabilities" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Equity" type="{http://www.intuit.com/sb/cdm/qboReports}ReportAccount" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="TotalEquity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="TotalLiabilitiesAndEquity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QboBalanceSheetReportResponse", namespace = "http://www.intuit.com/sb/cdm/qboReports", propOrder = {
    "assets",
    "totalAssets",
    "liabilitiesAndEquity",
    "totalLiabilitiesAndEquity"
})
public class QboBalanceSheetReportResponse
    implements Serializable, Equals, HashCode
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "Assets", required = true)
    protected QboBalanceSheetReportResponse.Assets assets;
    @XmlElement(name = "TotalAssets", required = true)
    protected String totalAssets;
    @XmlElement(name = "LiabilitiesAndEquity", required = true)
    protected QboBalanceSheetReportResponse.LiabilitiesAndEquity liabilitiesAndEquity;
    @XmlElement(name = "TotalLiabilitiesAndEquity", required = true)
    protected String totalLiabilitiesAndEquity;

    /**
     * Gets the value of the assets property.
     * 
     * @return
     *     possible object is
     *     {@link QboBalanceSheetReportResponse.Assets }
     *     
     */
    public QboBalanceSheetReportResponse.Assets getAssets() {
        return assets;
    }

    /**
     * Sets the value of the assets property.
     * 
     * @param value
     *     allowed object is
     *     {@link QboBalanceSheetReportResponse.Assets }
     *     
     */
    public void setAssets(QboBalanceSheetReportResponse.Assets value) {
        this.assets = value;
    }

    /**
     * Gets the value of the totalAssets property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalAssets() {
        return totalAssets;
    }

    /**
     * Sets the value of the totalAssets property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalAssets(String value) {
        this.totalAssets = value;
    }

    /**
     * Gets the value of the liabilitiesAndEquity property.
     * 
     * @return
     *     possible object is
     *     {@link QboBalanceSheetReportResponse.LiabilitiesAndEquity }
     *     
     */
    public QboBalanceSheetReportResponse.LiabilitiesAndEquity getLiabilitiesAndEquity() {
        return liabilitiesAndEquity;
    }

    /**
     * Sets the value of the liabilitiesAndEquity property.
     * 
     * @param value
     *     allowed object is
     *     {@link QboBalanceSheetReportResponse.LiabilitiesAndEquity }
     *     
     */
    public void setLiabilitiesAndEquity(QboBalanceSheetReportResponse.LiabilitiesAndEquity value) {
        this.liabilitiesAndEquity = value;
    }

    /**
     * Gets the value of the totalLiabilitiesAndEquity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalLiabilitiesAndEquity() {
        return totalLiabilitiesAndEquity;
    }

    /**
     * Sets the value of the totalLiabilitiesAndEquity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalLiabilitiesAndEquity(String value) {
        this.totalLiabilitiesAndEquity = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof QboBalanceSheetReportResponse)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final QboBalanceSheetReportResponse that = ((QboBalanceSheetReportResponse) object);
        {
            QboBalanceSheetReportResponse.Assets lhsAssets;
            lhsAssets = this.getAssets();
            QboBalanceSheetReportResponse.Assets rhsAssets;
            rhsAssets = that.getAssets();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "assets", lhsAssets), LocatorUtils.property(thatLocator, "assets", rhsAssets), lhsAssets, rhsAssets)) {
                return false;
            }
        }
        {
            String lhsTotalAssets;
            lhsTotalAssets = this.getTotalAssets();
            String rhsTotalAssets;
            rhsTotalAssets = that.getTotalAssets();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "totalAssets", lhsTotalAssets), LocatorUtils.property(thatLocator, "totalAssets", rhsTotalAssets), lhsTotalAssets, rhsTotalAssets)) {
                return false;
            }
        }
        {
            QboBalanceSheetReportResponse.LiabilitiesAndEquity lhsLiabilitiesAndEquity;
            lhsLiabilitiesAndEquity = this.getLiabilitiesAndEquity();
            QboBalanceSheetReportResponse.LiabilitiesAndEquity rhsLiabilitiesAndEquity;
            rhsLiabilitiesAndEquity = that.getLiabilitiesAndEquity();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "liabilitiesAndEquity", lhsLiabilitiesAndEquity), LocatorUtils.property(thatLocator, "liabilitiesAndEquity", rhsLiabilitiesAndEquity), lhsLiabilitiesAndEquity, rhsLiabilitiesAndEquity)) {
                return false;
            }
        }
        {
            String lhsTotalLiabilitiesAndEquity;
            lhsTotalLiabilitiesAndEquity = this.getTotalLiabilitiesAndEquity();
            String rhsTotalLiabilitiesAndEquity;
            rhsTotalLiabilitiesAndEquity = that.getTotalLiabilitiesAndEquity();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "totalLiabilitiesAndEquity", lhsTotalLiabilitiesAndEquity), LocatorUtils.property(thatLocator, "totalLiabilitiesAndEquity", rhsTotalLiabilitiesAndEquity), lhsTotalLiabilitiesAndEquity, rhsTotalLiabilitiesAndEquity)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            QboBalanceSheetReportResponse.Assets theAssets;
            theAssets = this.getAssets();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "assets", theAssets), currentHashCode, theAssets);
        }
        {
            String theTotalAssets;
            theTotalAssets = this.getTotalAssets();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "totalAssets", theTotalAssets), currentHashCode, theTotalAssets);
        }
        {
            QboBalanceSheetReportResponse.LiabilitiesAndEquity theLiabilitiesAndEquity;
            theLiabilitiesAndEquity = this.getLiabilitiesAndEquity();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "liabilitiesAndEquity", theLiabilitiesAndEquity), currentHashCode, theLiabilitiesAndEquity);
        }
        {
            String theTotalLiabilitiesAndEquity;
            theTotalLiabilitiesAndEquity = this.getTotalLiabilitiesAndEquity();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "totalLiabilitiesAndEquity", theTotalLiabilitiesAndEquity), currentHashCode, theTotalLiabilitiesAndEquity);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CurrentAssets">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="BankAccounts" type="{http://www.intuit.com/sb/cdm/qboReports}ReportAccount" maxOccurs="unbounded" minOccurs="0"/>
     *                   &lt;element name="TotalBankAccounts" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="AccountsReceivable" type="{http://www.intuit.com/sb/cdm/qboReports}ReportAccount" maxOccurs="unbounded" minOccurs="0"/>
     *                   &lt;element name="TotalAccountsReceivable" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="OtherCurrentAssets" type="{http://www.intuit.com/sb/cdm/qboReports}ReportAccount" maxOccurs="unbounded" minOccurs="0"/>
     *                   &lt;element name="TotalOtherCurrentAssets" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="TotalCurrentAssets" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="FixedAssets" type="{http://www.intuit.com/sb/cdm/qboReports}ReportAccount" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="TotalFixedAssets" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="OtherAssets" type="{http://www.intuit.com/sb/cdm/qboReports}ReportAccount" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="TotalOtherAssets" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "currentAssets",
        "totalCurrentAssets",
        "fixedAssets",
        "totalFixedAssets",
        "otherAssets",
        "totalOtherAssets"
    })
    public static class Assets
        implements Serializable, Equals, HashCode
    {

        private final static long serialVersionUID = 1L;
        @XmlElement(name = "CurrentAssets", namespace = "http://www.intuit.com/sb/cdm/qboReports", required = true)
        protected QboBalanceSheetReportResponse.Assets.CurrentAssets currentAssets;
        @XmlElement(name = "TotalCurrentAssets", namespace = "http://www.intuit.com/sb/cdm/qboReports", required = true)
        protected String totalCurrentAssets;
        @XmlElement(name = "FixedAssets", namespace = "http://www.intuit.com/sb/cdm/qboReports")
        protected List<ReportAccount> fixedAssets;
        @XmlElement(name = "TotalFixedAssets", namespace = "http://www.intuit.com/sb/cdm/qboReports", required = true)
        protected String totalFixedAssets;
        @XmlElement(name = "OtherAssets", namespace = "http://www.intuit.com/sb/cdm/qboReports")
        protected List<ReportAccount> otherAssets;
        @XmlElement(name = "TotalOtherAssets", namespace = "http://www.intuit.com/sb/cdm/qboReports", required = true)
        protected String totalOtherAssets;

        /**
         * Gets the value of the currentAssets property.
         * 
         * @return
         *     possible object is
         *     {@link QboBalanceSheetReportResponse.Assets.CurrentAssets }
         *     
         */
        public QboBalanceSheetReportResponse.Assets.CurrentAssets getCurrentAssets() {
            return currentAssets;
        }

        /**
         * Sets the value of the currentAssets property.
         * 
         * @param value
         *     allowed object is
         *     {@link QboBalanceSheetReportResponse.Assets.CurrentAssets }
         *     
         */
        public void setCurrentAssets(QboBalanceSheetReportResponse.Assets.CurrentAssets value) {
            this.currentAssets = value;
        }

        /**
         * Gets the value of the totalCurrentAssets property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTotalCurrentAssets() {
            return totalCurrentAssets;
        }

        /**
         * Sets the value of the totalCurrentAssets property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTotalCurrentAssets(String value) {
            this.totalCurrentAssets = value;
        }

        /**
         * Gets the value of the fixedAssets property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the fixedAssets property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFixedAssets().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ReportAccount }
         * 
         * 
         */
        public List<ReportAccount> getFixedAssets() {
            if (fixedAssets == null) {
                fixedAssets = new ArrayList<ReportAccount>();
            }
            return this.fixedAssets;
        }

        /**
         * Gets the value of the totalFixedAssets property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTotalFixedAssets() {
            return totalFixedAssets;
        }

        /**
         * Sets the value of the totalFixedAssets property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTotalFixedAssets(String value) {
            this.totalFixedAssets = value;
        }

        /**
         * Gets the value of the otherAssets property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the otherAssets property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOtherAssets().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ReportAccount }
         * 
         * 
         */
        public List<ReportAccount> getOtherAssets() {
            if (otherAssets == null) {
                otherAssets = new ArrayList<ReportAccount>();
            }
            return this.otherAssets;
        }

        /**
         * Gets the value of the totalOtherAssets property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTotalOtherAssets() {
            return totalOtherAssets;
        }

        /**
         * Sets the value of the totalOtherAssets property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTotalOtherAssets(String value) {
            this.totalOtherAssets = value;
        }

        /**
         * Sets the value of the fixedAssets property.
         * 
         * @param fixedAssets
         *     allowed object is
         *     {@link ReportAccount }
         *     
         */
        public void setFixedAssets(List<ReportAccount> fixedAssets) {
            this.fixedAssets = fixedAssets;
        }

        /**
         * Sets the value of the otherAssets property.
         * 
         * @param otherAssets
         *     allowed object is
         *     {@link ReportAccount }
         *     
         */
        public void setOtherAssets(List<ReportAccount> otherAssets) {
            this.otherAssets = otherAssets;
        }

        public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
            if (!(object instanceof QboBalanceSheetReportResponse.Assets)) {
                return false;
            }
            if (this == object) {
                return true;
            }
            final QboBalanceSheetReportResponse.Assets that = ((QboBalanceSheetReportResponse.Assets) object);
            {
                QboBalanceSheetReportResponse.Assets.CurrentAssets lhsCurrentAssets;
                lhsCurrentAssets = this.getCurrentAssets();
                QboBalanceSheetReportResponse.Assets.CurrentAssets rhsCurrentAssets;
                rhsCurrentAssets = that.getCurrentAssets();
                if (!strategy.equals(LocatorUtils.property(thisLocator, "currentAssets", lhsCurrentAssets), LocatorUtils.property(thatLocator, "currentAssets", rhsCurrentAssets), lhsCurrentAssets, rhsCurrentAssets)) {
                    return false;
                }
            }
            {
                String lhsTotalCurrentAssets;
                lhsTotalCurrentAssets = this.getTotalCurrentAssets();
                String rhsTotalCurrentAssets;
                rhsTotalCurrentAssets = that.getTotalCurrentAssets();
                if (!strategy.equals(LocatorUtils.property(thisLocator, "totalCurrentAssets", lhsTotalCurrentAssets), LocatorUtils.property(thatLocator, "totalCurrentAssets", rhsTotalCurrentAssets), lhsTotalCurrentAssets, rhsTotalCurrentAssets)) {
                    return false;
                }
            }
            {
                List<ReportAccount> lhsFixedAssets;
                lhsFixedAssets = this.getFixedAssets();
                List<ReportAccount> rhsFixedAssets;
                rhsFixedAssets = that.getFixedAssets();
                if (!strategy.equals(LocatorUtils.property(thisLocator, "fixedAssets", lhsFixedAssets), LocatorUtils.property(thatLocator, "fixedAssets", rhsFixedAssets), lhsFixedAssets, rhsFixedAssets)) {
                    return false;
                }
            }
            {
                String lhsTotalFixedAssets;
                lhsTotalFixedAssets = this.getTotalFixedAssets();
                String rhsTotalFixedAssets;
                rhsTotalFixedAssets = that.getTotalFixedAssets();
                if (!strategy.equals(LocatorUtils.property(thisLocator, "totalFixedAssets", lhsTotalFixedAssets), LocatorUtils.property(thatLocator, "totalFixedAssets", rhsTotalFixedAssets), lhsTotalFixedAssets, rhsTotalFixedAssets)) {
                    return false;
                }
            }
            {
                List<ReportAccount> lhsOtherAssets;
                lhsOtherAssets = this.getOtherAssets();
                List<ReportAccount> rhsOtherAssets;
                rhsOtherAssets = that.getOtherAssets();
                if (!strategy.equals(LocatorUtils.property(thisLocator, "otherAssets", lhsOtherAssets), LocatorUtils.property(thatLocator, "otherAssets", rhsOtherAssets), lhsOtherAssets, rhsOtherAssets)) {
                    return false;
                }
            }
            {
                String lhsTotalOtherAssets;
                lhsTotalOtherAssets = this.getTotalOtherAssets();
                String rhsTotalOtherAssets;
                rhsTotalOtherAssets = that.getTotalOtherAssets();
                if (!strategy.equals(LocatorUtils.property(thisLocator, "totalOtherAssets", lhsTotalOtherAssets), LocatorUtils.property(thatLocator, "totalOtherAssets", rhsTotalOtherAssets), lhsTotalOtherAssets, rhsTotalOtherAssets)) {
                    return false;
                }
            }
            return true;
        }

        public boolean equals(Object object) {
            final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
            return equals(null, null, object, strategy);
        }

        public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
            int currentHashCode = 1;
            {
                QboBalanceSheetReportResponse.Assets.CurrentAssets theCurrentAssets;
                theCurrentAssets = this.getCurrentAssets();
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "currentAssets", theCurrentAssets), currentHashCode, theCurrentAssets);
            }
            {
                String theTotalCurrentAssets;
                theTotalCurrentAssets = this.getTotalCurrentAssets();
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "totalCurrentAssets", theTotalCurrentAssets), currentHashCode, theTotalCurrentAssets);
            }
            {
                List<ReportAccount> theFixedAssets;
                theFixedAssets = this.getFixedAssets();
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "fixedAssets", theFixedAssets), currentHashCode, theFixedAssets);
            }
            {
                String theTotalFixedAssets;
                theTotalFixedAssets = this.getTotalFixedAssets();
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "totalFixedAssets", theTotalFixedAssets), currentHashCode, theTotalFixedAssets);
            }
            {
                List<ReportAccount> theOtherAssets;
                theOtherAssets = this.getOtherAssets();
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "otherAssets", theOtherAssets), currentHashCode, theOtherAssets);
            }
            {
                String theTotalOtherAssets;
                theTotalOtherAssets = this.getTotalOtherAssets();
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "totalOtherAssets", theTotalOtherAssets), currentHashCode, theTotalOtherAssets);
            }
            return currentHashCode;
        }

        public int hashCode() {
            final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
            return this.hashCode(null, strategy);
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="BankAccounts" type="{http://www.intuit.com/sb/cdm/qboReports}ReportAccount" maxOccurs="unbounded" minOccurs="0"/>
         *         &lt;element name="TotalBankAccounts" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="AccountsReceivable" type="{http://www.intuit.com/sb/cdm/qboReports}ReportAccount" maxOccurs="unbounded" minOccurs="0"/>
         *         &lt;element name="TotalAccountsReceivable" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="OtherCurrentAssets" type="{http://www.intuit.com/sb/cdm/qboReports}ReportAccount" maxOccurs="unbounded" minOccurs="0"/>
         *         &lt;element name="TotalOtherCurrentAssets" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "bankAccounts",
            "totalBankAccounts",
            "accountsReceivable",
            "totalAccountsReceivable",
            "otherCurrentAssets",
            "totalOtherCurrentAssets"
        })
        public static class CurrentAssets
            implements Serializable, Equals, HashCode
        {

            private final static long serialVersionUID = 1L;
            @XmlElement(name = "BankAccounts", namespace = "http://www.intuit.com/sb/cdm/qboReports")
            protected List<ReportAccount> bankAccounts;
            @XmlElement(name = "TotalBankAccounts", namespace = "http://www.intuit.com/sb/cdm/qboReports", required = true)
            protected String totalBankAccounts;
            @XmlElement(name = "AccountsReceivable", namespace = "http://www.intuit.com/sb/cdm/qboReports")
            protected List<ReportAccount> accountsReceivable;
            @XmlElement(name = "TotalAccountsReceivable", namespace = "http://www.intuit.com/sb/cdm/qboReports", required = true)
            protected String totalAccountsReceivable;
            @XmlElement(name = "OtherCurrentAssets", namespace = "http://www.intuit.com/sb/cdm/qboReports")
            protected List<ReportAccount> otherCurrentAssets;
            @XmlElement(name = "TotalOtherCurrentAssets", namespace = "http://www.intuit.com/sb/cdm/qboReports", required = true)
            protected String totalOtherCurrentAssets;

            /**
             * Gets the value of the bankAccounts property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the bankAccounts property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getBankAccounts().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link ReportAccount }
             * 
             * 
             */
            public List<ReportAccount> getBankAccounts() {
                if (bankAccounts == null) {
                    bankAccounts = new ArrayList<ReportAccount>();
                }
                return this.bankAccounts;
            }

            /**
             * Gets the value of the totalBankAccounts property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTotalBankAccounts() {
                return totalBankAccounts;
            }

            /**
             * Sets the value of the totalBankAccounts property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTotalBankAccounts(String value) {
                this.totalBankAccounts = value;
            }

            /**
             * Gets the value of the accountsReceivable property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the accountsReceivable property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getAccountsReceivable().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link ReportAccount }
             * 
             * 
             */
            public List<ReportAccount> getAccountsReceivable() {
                if (accountsReceivable == null) {
                    accountsReceivable = new ArrayList<ReportAccount>();
                }
                return this.accountsReceivable;
            }

            /**
             * Gets the value of the totalAccountsReceivable property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTotalAccountsReceivable() {
                return totalAccountsReceivable;
            }

            /**
             * Sets the value of the totalAccountsReceivable property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTotalAccountsReceivable(String value) {
                this.totalAccountsReceivable = value;
            }

            /**
             * Gets the value of the otherCurrentAssets property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the otherCurrentAssets property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getOtherCurrentAssets().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link ReportAccount }
             * 
             * 
             */
            public List<ReportAccount> getOtherCurrentAssets() {
                if (otherCurrentAssets == null) {
                    otherCurrentAssets = new ArrayList<ReportAccount>();
                }
                return this.otherCurrentAssets;
            }

            /**
             * Gets the value of the totalOtherCurrentAssets property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTotalOtherCurrentAssets() {
                return totalOtherCurrentAssets;
            }

            /**
             * Sets the value of the totalOtherCurrentAssets property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTotalOtherCurrentAssets(String value) {
                this.totalOtherCurrentAssets = value;
            }

            /**
             * Sets the value of the bankAccounts property.
             * 
             * @param bankAccounts
             *     allowed object is
             *     {@link ReportAccount }
             *     
             */
            public void setBankAccounts(List<ReportAccount> bankAccounts) {
                this.bankAccounts = bankAccounts;
            }

            /**
             * Sets the value of the accountsReceivable property.
             * 
             * @param accountsReceivable
             *     allowed object is
             *     {@link ReportAccount }
             *     
             */
            public void setAccountsReceivable(List<ReportAccount> accountsReceivable) {
                this.accountsReceivable = accountsReceivable;
            }

            /**
             * Sets the value of the otherCurrentAssets property.
             * 
             * @param otherCurrentAssets
             *     allowed object is
             *     {@link ReportAccount }
             *     
             */
            public void setOtherCurrentAssets(List<ReportAccount> otherCurrentAssets) {
                this.otherCurrentAssets = otherCurrentAssets;
            }

            public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
                if (!(object instanceof QboBalanceSheetReportResponse.Assets.CurrentAssets)) {
                    return false;
                }
                if (this == object) {
                    return true;
                }
                final QboBalanceSheetReportResponse.Assets.CurrentAssets that = ((QboBalanceSheetReportResponse.Assets.CurrentAssets) object);
                {
                    List<ReportAccount> lhsBankAccounts;
                    lhsBankAccounts = this.getBankAccounts();
                    List<ReportAccount> rhsBankAccounts;
                    rhsBankAccounts = that.getBankAccounts();
                    if (!strategy.equals(LocatorUtils.property(thisLocator, "bankAccounts", lhsBankAccounts), LocatorUtils.property(thatLocator, "bankAccounts", rhsBankAccounts), lhsBankAccounts, rhsBankAccounts)) {
                        return false;
                    }
                }
                {
                    String lhsTotalBankAccounts;
                    lhsTotalBankAccounts = this.getTotalBankAccounts();
                    String rhsTotalBankAccounts;
                    rhsTotalBankAccounts = that.getTotalBankAccounts();
                    if (!strategy.equals(LocatorUtils.property(thisLocator, "totalBankAccounts", lhsTotalBankAccounts), LocatorUtils.property(thatLocator, "totalBankAccounts", rhsTotalBankAccounts), lhsTotalBankAccounts, rhsTotalBankAccounts)) {
                        return false;
                    }
                }
                {
                    List<ReportAccount> lhsAccountsReceivable;
                    lhsAccountsReceivable = this.getAccountsReceivable();
                    List<ReportAccount> rhsAccountsReceivable;
                    rhsAccountsReceivable = that.getAccountsReceivable();
                    if (!strategy.equals(LocatorUtils.property(thisLocator, "accountsReceivable", lhsAccountsReceivable), LocatorUtils.property(thatLocator, "accountsReceivable", rhsAccountsReceivable), lhsAccountsReceivable, rhsAccountsReceivable)) {
                        return false;
                    }
                }
                {
                    String lhsTotalAccountsReceivable;
                    lhsTotalAccountsReceivable = this.getTotalAccountsReceivable();
                    String rhsTotalAccountsReceivable;
                    rhsTotalAccountsReceivable = that.getTotalAccountsReceivable();
                    if (!strategy.equals(LocatorUtils.property(thisLocator, "totalAccountsReceivable", lhsTotalAccountsReceivable), LocatorUtils.property(thatLocator, "totalAccountsReceivable", rhsTotalAccountsReceivable), lhsTotalAccountsReceivable, rhsTotalAccountsReceivable)) {
                        return false;
                    }
                }
                {
                    List<ReportAccount> lhsOtherCurrentAssets;
                    lhsOtherCurrentAssets = this.getOtherCurrentAssets();
                    List<ReportAccount> rhsOtherCurrentAssets;
                    rhsOtherCurrentAssets = that.getOtherCurrentAssets();
                    if (!strategy.equals(LocatorUtils.property(thisLocator, "otherCurrentAssets", lhsOtherCurrentAssets), LocatorUtils.property(thatLocator, "otherCurrentAssets", rhsOtherCurrentAssets), lhsOtherCurrentAssets, rhsOtherCurrentAssets)) {
                        return false;
                    }
                }
                {
                    String lhsTotalOtherCurrentAssets;
                    lhsTotalOtherCurrentAssets = this.getTotalOtherCurrentAssets();
                    String rhsTotalOtherCurrentAssets;
                    rhsTotalOtherCurrentAssets = that.getTotalOtherCurrentAssets();
                    if (!strategy.equals(LocatorUtils.property(thisLocator, "totalOtherCurrentAssets", lhsTotalOtherCurrentAssets), LocatorUtils.property(thatLocator, "totalOtherCurrentAssets", rhsTotalOtherCurrentAssets), lhsTotalOtherCurrentAssets, rhsTotalOtherCurrentAssets)) {
                        return false;
                    }
                }
                return true;
            }

            public boolean equals(Object object) {
                final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
                return equals(null, null, object, strategy);
            }

            public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
                int currentHashCode = 1;
                {
                    List<ReportAccount> theBankAccounts;
                    theBankAccounts = this.getBankAccounts();
                    currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "bankAccounts", theBankAccounts), currentHashCode, theBankAccounts);
                }
                {
                    String theTotalBankAccounts;
                    theTotalBankAccounts = this.getTotalBankAccounts();
                    currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "totalBankAccounts", theTotalBankAccounts), currentHashCode, theTotalBankAccounts);
                }
                {
                    List<ReportAccount> theAccountsReceivable;
                    theAccountsReceivable = this.getAccountsReceivable();
                    currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "accountsReceivable", theAccountsReceivable), currentHashCode, theAccountsReceivable);
                }
                {
                    String theTotalAccountsReceivable;
                    theTotalAccountsReceivable = this.getTotalAccountsReceivable();
                    currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "totalAccountsReceivable", theTotalAccountsReceivable), currentHashCode, theTotalAccountsReceivable);
                }
                {
                    List<ReportAccount> theOtherCurrentAssets;
                    theOtherCurrentAssets = this.getOtherCurrentAssets();
                    currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "otherCurrentAssets", theOtherCurrentAssets), currentHashCode, theOtherCurrentAssets);
                }
                {
                    String theTotalOtherCurrentAssets;
                    theTotalOtherCurrentAssets = this.getTotalOtherCurrentAssets();
                    currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "totalOtherCurrentAssets", theTotalOtherCurrentAssets), currentHashCode, theTotalOtherCurrentAssets);
                }
                return currentHashCode;
            }

            public int hashCode() {
                final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
                return this.hashCode(null, strategy);
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Liabilities">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="CurrentLiabilities">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="AccountsPayable" type="{http://www.intuit.com/sb/cdm/qboReports}ReportAccount" maxOccurs="unbounded" minOccurs="0"/>
     *                             &lt;element name="TotalAccountsPayable" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="CreditCards" type="{http://www.intuit.com/sb/cdm/qboReports}ReportAccount" maxOccurs="unbounded" minOccurs="0"/>
     *                             &lt;element name="TotalCreditCards" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="OtherCurrentLiabilities" type="{http://www.intuit.com/sb/cdm/qboReports}ReportAccount" maxOccurs="unbounded" minOccurs="0"/>
     *                             &lt;element name="TotalOtherCurrentLiabilities" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="TotalCurrentLiabilities" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="LongTermLiabilities" type="{http://www.intuit.com/sb/cdm/qboReports}ReportAccount" maxOccurs="unbounded" minOccurs="0"/>
     *                   &lt;element name="TotalLongTermLiabilities" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="TotalLiabilities" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Equity" type="{http://www.intuit.com/sb/cdm/qboReports}ReportAccount" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="TotalEquity" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "liabilities",
        "totalLiabilities",
        "equity",
        "totalEquity"
    })
    public static class LiabilitiesAndEquity
        implements Serializable, Equals, HashCode
    {

        private final static long serialVersionUID = 1L;
        @XmlElement(name = "Liabilities", namespace = "http://www.intuit.com/sb/cdm/qboReports", required = true)
        protected QboBalanceSheetReportResponse.LiabilitiesAndEquity.Liabilities liabilities;
        @XmlElement(name = "TotalLiabilities", namespace = "http://www.intuit.com/sb/cdm/qboReports", required = true)
        protected String totalLiabilities;
        @XmlElement(name = "Equity", namespace = "http://www.intuit.com/sb/cdm/qboReports")
        protected List<ReportAccount> equity;
        @XmlElement(name = "TotalEquity", namespace = "http://www.intuit.com/sb/cdm/qboReports", required = true)
        protected String totalEquity;

        /**
         * Gets the value of the liabilities property.
         * 
         * @return
         *     possible object is
         *     {@link QboBalanceSheetReportResponse.LiabilitiesAndEquity.Liabilities }
         *     
         */
        public QboBalanceSheetReportResponse.LiabilitiesAndEquity.Liabilities getLiabilities() {
            return liabilities;
        }

        /**
         * Sets the value of the liabilities property.
         * 
         * @param value
         *     allowed object is
         *     {@link QboBalanceSheetReportResponse.LiabilitiesAndEquity.Liabilities }
         *     
         */
        public void setLiabilities(QboBalanceSheetReportResponse.LiabilitiesAndEquity.Liabilities value) {
            this.liabilities = value;
        }

        /**
         * Gets the value of the totalLiabilities property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTotalLiabilities() {
            return totalLiabilities;
        }

        /**
         * Sets the value of the totalLiabilities property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTotalLiabilities(String value) {
            this.totalLiabilities = value;
        }

        /**
         * Gets the value of the equity property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the equity property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEquity().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ReportAccount }
         * 
         * 
         */
        public List<ReportAccount> getEquity() {
            if (equity == null) {
                equity = new ArrayList<ReportAccount>();
            }
            return this.equity;
        }

        /**
         * Gets the value of the totalEquity property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTotalEquity() {
            return totalEquity;
        }

        /**
         * Sets the value of the totalEquity property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTotalEquity(String value) {
            this.totalEquity = value;
        }

        /**
         * Sets the value of the equity property.
         * 
         * @param equity
         *     allowed object is
         *     {@link ReportAccount }
         *     
         */
        public void setEquity(List<ReportAccount> equity) {
            this.equity = equity;
        }

        public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
            if (!(object instanceof QboBalanceSheetReportResponse.LiabilitiesAndEquity)) {
                return false;
            }
            if (this == object) {
                return true;
            }
            final QboBalanceSheetReportResponse.LiabilitiesAndEquity that = ((QboBalanceSheetReportResponse.LiabilitiesAndEquity) object);
            {
                QboBalanceSheetReportResponse.LiabilitiesAndEquity.Liabilities lhsLiabilities;
                lhsLiabilities = this.getLiabilities();
                QboBalanceSheetReportResponse.LiabilitiesAndEquity.Liabilities rhsLiabilities;
                rhsLiabilities = that.getLiabilities();
                if (!strategy.equals(LocatorUtils.property(thisLocator, "liabilities", lhsLiabilities), LocatorUtils.property(thatLocator, "liabilities", rhsLiabilities), lhsLiabilities, rhsLiabilities)) {
                    return false;
                }
            }
            {
                String lhsTotalLiabilities;
                lhsTotalLiabilities = this.getTotalLiabilities();
                String rhsTotalLiabilities;
                rhsTotalLiabilities = that.getTotalLiabilities();
                if (!strategy.equals(LocatorUtils.property(thisLocator, "totalLiabilities", lhsTotalLiabilities), LocatorUtils.property(thatLocator, "totalLiabilities", rhsTotalLiabilities), lhsTotalLiabilities, rhsTotalLiabilities)) {
                    return false;
                }
            }
            {
                List<ReportAccount> lhsEquity;
                lhsEquity = this.getEquity();
                List<ReportAccount> rhsEquity;
                rhsEquity = that.getEquity();
                if (!strategy.equals(LocatorUtils.property(thisLocator, "equity", lhsEquity), LocatorUtils.property(thatLocator, "equity", rhsEquity), lhsEquity, rhsEquity)) {
                    return false;
                }
            }
            {
                String lhsTotalEquity;
                lhsTotalEquity = this.getTotalEquity();
                String rhsTotalEquity;
                rhsTotalEquity = that.getTotalEquity();
                if (!strategy.equals(LocatorUtils.property(thisLocator, "totalEquity", lhsTotalEquity), LocatorUtils.property(thatLocator, "totalEquity", rhsTotalEquity), lhsTotalEquity, rhsTotalEquity)) {
                    return false;
                }
            }
            return true;
        }

        public boolean equals(Object object) {
            final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
            return equals(null, null, object, strategy);
        }

        public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
            int currentHashCode = 1;
            {
                QboBalanceSheetReportResponse.LiabilitiesAndEquity.Liabilities theLiabilities;
                theLiabilities = this.getLiabilities();
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "liabilities", theLiabilities), currentHashCode, theLiabilities);
            }
            {
                String theTotalLiabilities;
                theTotalLiabilities = this.getTotalLiabilities();
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "totalLiabilities", theTotalLiabilities), currentHashCode, theTotalLiabilities);
            }
            {
                List<ReportAccount> theEquity;
                theEquity = this.getEquity();
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "equity", theEquity), currentHashCode, theEquity);
            }
            {
                String theTotalEquity;
                theTotalEquity = this.getTotalEquity();
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "totalEquity", theTotalEquity), currentHashCode, theTotalEquity);
            }
            return currentHashCode;
        }

        public int hashCode() {
            final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
            return this.hashCode(null, strategy);
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="CurrentLiabilities">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="AccountsPayable" type="{http://www.intuit.com/sb/cdm/qboReports}ReportAccount" maxOccurs="unbounded" minOccurs="0"/>
         *                   &lt;element name="TotalAccountsPayable" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="CreditCards" type="{http://www.intuit.com/sb/cdm/qboReports}ReportAccount" maxOccurs="unbounded" minOccurs="0"/>
         *                   &lt;element name="TotalCreditCards" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="OtherCurrentLiabilities" type="{http://www.intuit.com/sb/cdm/qboReports}ReportAccount" maxOccurs="unbounded" minOccurs="0"/>
         *                   &lt;element name="TotalOtherCurrentLiabilities" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="TotalCurrentLiabilities" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="LongTermLiabilities" type="{http://www.intuit.com/sb/cdm/qboReports}ReportAccount" maxOccurs="unbounded" minOccurs="0"/>
         *         &lt;element name="TotalLongTermLiabilities" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "currentLiabilities",
            "totalCurrentLiabilities",
            "longTermLiabilities",
            "totalLongTermLiabilities"
        })
        public static class Liabilities
            implements Serializable, Equals, HashCode
        {

            private final static long serialVersionUID = 1L;
            @XmlElement(name = "CurrentLiabilities", namespace = "http://www.intuit.com/sb/cdm/qboReports", required = true)
            protected QboBalanceSheetReportResponse.LiabilitiesAndEquity.Liabilities.CurrentLiabilities currentLiabilities;
            @XmlElement(name = "TotalCurrentLiabilities", namespace = "http://www.intuit.com/sb/cdm/qboReports", required = true)
            protected String totalCurrentLiabilities;
            @XmlElement(name = "LongTermLiabilities", namespace = "http://www.intuit.com/sb/cdm/qboReports")
            protected List<ReportAccount> longTermLiabilities;
            @XmlElement(name = "TotalLongTermLiabilities", namespace = "http://www.intuit.com/sb/cdm/qboReports", required = true)
            protected String totalLongTermLiabilities;

            /**
             * Gets the value of the currentLiabilities property.
             * 
             * @return
             *     possible object is
             *     {@link QboBalanceSheetReportResponse.LiabilitiesAndEquity.Liabilities.CurrentLiabilities }
             *     
             */
            public QboBalanceSheetReportResponse.LiabilitiesAndEquity.Liabilities.CurrentLiabilities getCurrentLiabilities() {
                return currentLiabilities;
            }

            /**
             * Sets the value of the currentLiabilities property.
             * 
             * @param value
             *     allowed object is
             *     {@link QboBalanceSheetReportResponse.LiabilitiesAndEquity.Liabilities.CurrentLiabilities }
             *     
             */
            public void setCurrentLiabilities(QboBalanceSheetReportResponse.LiabilitiesAndEquity.Liabilities.CurrentLiabilities value) {
                this.currentLiabilities = value;
            }

            /**
             * Gets the value of the totalCurrentLiabilities property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTotalCurrentLiabilities() {
                return totalCurrentLiabilities;
            }

            /**
             * Sets the value of the totalCurrentLiabilities property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTotalCurrentLiabilities(String value) {
                this.totalCurrentLiabilities = value;
            }

            /**
             * Gets the value of the longTermLiabilities property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the longTermLiabilities property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getLongTermLiabilities().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link ReportAccount }
             * 
             * 
             */
            public List<ReportAccount> getLongTermLiabilities() {
                if (longTermLiabilities == null) {
                    longTermLiabilities = new ArrayList<ReportAccount>();
                }
                return this.longTermLiabilities;
            }

            /**
             * Gets the value of the totalLongTermLiabilities property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTotalLongTermLiabilities() {
                return totalLongTermLiabilities;
            }

            /**
             * Sets the value of the totalLongTermLiabilities property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTotalLongTermLiabilities(String value) {
                this.totalLongTermLiabilities = value;
            }

            /**
             * Sets the value of the longTermLiabilities property.
             * 
             * @param longTermLiabilities
             *     allowed object is
             *     {@link ReportAccount }
             *     
             */
            public void setLongTermLiabilities(List<ReportAccount> longTermLiabilities) {
                this.longTermLiabilities = longTermLiabilities;
            }

            public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
                if (!(object instanceof QboBalanceSheetReportResponse.LiabilitiesAndEquity.Liabilities)) {
                    return false;
                }
                if (this == object) {
                    return true;
                }
                final QboBalanceSheetReportResponse.LiabilitiesAndEquity.Liabilities that = ((QboBalanceSheetReportResponse.LiabilitiesAndEquity.Liabilities) object);
                {
                    QboBalanceSheetReportResponse.LiabilitiesAndEquity.Liabilities.CurrentLiabilities lhsCurrentLiabilities;
                    lhsCurrentLiabilities = this.getCurrentLiabilities();
                    QboBalanceSheetReportResponse.LiabilitiesAndEquity.Liabilities.CurrentLiabilities rhsCurrentLiabilities;
                    rhsCurrentLiabilities = that.getCurrentLiabilities();
                    if (!strategy.equals(LocatorUtils.property(thisLocator, "currentLiabilities", lhsCurrentLiabilities), LocatorUtils.property(thatLocator, "currentLiabilities", rhsCurrentLiabilities), lhsCurrentLiabilities, rhsCurrentLiabilities)) {
                        return false;
                    }
                }
                {
                    String lhsTotalCurrentLiabilities;
                    lhsTotalCurrentLiabilities = this.getTotalCurrentLiabilities();
                    String rhsTotalCurrentLiabilities;
                    rhsTotalCurrentLiabilities = that.getTotalCurrentLiabilities();
                    if (!strategy.equals(LocatorUtils.property(thisLocator, "totalCurrentLiabilities", lhsTotalCurrentLiabilities), LocatorUtils.property(thatLocator, "totalCurrentLiabilities", rhsTotalCurrentLiabilities), lhsTotalCurrentLiabilities, rhsTotalCurrentLiabilities)) {
                        return false;
                    }
                }
                {
                    List<ReportAccount> lhsLongTermLiabilities;
                    lhsLongTermLiabilities = this.getLongTermLiabilities();
                    List<ReportAccount> rhsLongTermLiabilities;
                    rhsLongTermLiabilities = that.getLongTermLiabilities();
                    if (!strategy.equals(LocatorUtils.property(thisLocator, "longTermLiabilities", lhsLongTermLiabilities), LocatorUtils.property(thatLocator, "longTermLiabilities", rhsLongTermLiabilities), lhsLongTermLiabilities, rhsLongTermLiabilities)) {
                        return false;
                    }
                }
                {
                    String lhsTotalLongTermLiabilities;
                    lhsTotalLongTermLiabilities = this.getTotalLongTermLiabilities();
                    String rhsTotalLongTermLiabilities;
                    rhsTotalLongTermLiabilities = that.getTotalLongTermLiabilities();
                    if (!strategy.equals(LocatorUtils.property(thisLocator, "totalLongTermLiabilities", lhsTotalLongTermLiabilities), LocatorUtils.property(thatLocator, "totalLongTermLiabilities", rhsTotalLongTermLiabilities), lhsTotalLongTermLiabilities, rhsTotalLongTermLiabilities)) {
                        return false;
                    }
                }
                return true;
            }

            public boolean equals(Object object) {
                final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
                return equals(null, null, object, strategy);
            }

            public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
                int currentHashCode = 1;
                {
                    QboBalanceSheetReportResponse.LiabilitiesAndEquity.Liabilities.CurrentLiabilities theCurrentLiabilities;
                    theCurrentLiabilities = this.getCurrentLiabilities();
                    currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "currentLiabilities", theCurrentLiabilities), currentHashCode, theCurrentLiabilities);
                }
                {
                    String theTotalCurrentLiabilities;
                    theTotalCurrentLiabilities = this.getTotalCurrentLiabilities();
                    currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "totalCurrentLiabilities", theTotalCurrentLiabilities), currentHashCode, theTotalCurrentLiabilities);
                }
                {
                    List<ReportAccount> theLongTermLiabilities;
                    theLongTermLiabilities = this.getLongTermLiabilities();
                    currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "longTermLiabilities", theLongTermLiabilities), currentHashCode, theLongTermLiabilities);
                }
                {
                    String theTotalLongTermLiabilities;
                    theTotalLongTermLiabilities = this.getTotalLongTermLiabilities();
                    currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "totalLongTermLiabilities", theTotalLongTermLiabilities), currentHashCode, theTotalLongTermLiabilities);
                }
                return currentHashCode;
            }

            public int hashCode() {
                final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
                return this.hashCode(null, strategy);
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="AccountsPayable" type="{http://www.intuit.com/sb/cdm/qboReports}ReportAccount" maxOccurs="unbounded" minOccurs="0"/>
             *         &lt;element name="TotalAccountsPayable" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="CreditCards" type="{http://www.intuit.com/sb/cdm/qboReports}ReportAccount" maxOccurs="unbounded" minOccurs="0"/>
             *         &lt;element name="TotalCreditCards" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="OtherCurrentLiabilities" type="{http://www.intuit.com/sb/cdm/qboReports}ReportAccount" maxOccurs="unbounded" minOccurs="0"/>
             *         &lt;element name="TotalOtherCurrentLiabilities" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "accountsPayable",
                "totalAccountsPayable",
                "creditCards",
                "totalCreditCards",
                "otherCurrentLiabilities",
                "totalOtherCurrentLiabilities"
            })
            public static class CurrentLiabilities
                implements Serializable, Equals, HashCode
            {

                private final static long serialVersionUID = 1L;
                @XmlElement(name = "AccountsPayable", namespace = "http://www.intuit.com/sb/cdm/qboReports")
                protected List<ReportAccount> accountsPayable;
                @XmlElement(name = "TotalAccountsPayable", namespace = "http://www.intuit.com/sb/cdm/qboReports", required = true)
                protected String totalAccountsPayable;
                @XmlElement(name = "CreditCards", namespace = "http://www.intuit.com/sb/cdm/qboReports")
                protected List<ReportAccount> creditCards;
                @XmlElement(name = "TotalCreditCards", namespace = "http://www.intuit.com/sb/cdm/qboReports", required = true)
                protected String totalCreditCards;
                @XmlElement(name = "OtherCurrentLiabilities", namespace = "http://www.intuit.com/sb/cdm/qboReports")
                protected List<ReportAccount> otherCurrentLiabilities;
                @XmlElement(name = "TotalOtherCurrentLiabilities", namespace = "http://www.intuit.com/sb/cdm/qboReports", required = true)
                protected String totalOtherCurrentLiabilities;

                /**
                 * Gets the value of the accountsPayable property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the accountsPayable property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getAccountsPayable().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link ReportAccount }
                 * 
                 * 
                 */
                public List<ReportAccount> getAccountsPayable() {
                    if (accountsPayable == null) {
                        accountsPayable = new ArrayList<ReportAccount>();
                    }
                    return this.accountsPayable;
                }

                /**
                 * Gets the value of the totalAccountsPayable property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTotalAccountsPayable() {
                    return totalAccountsPayable;
                }

                /**
                 * Sets the value of the totalAccountsPayable property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTotalAccountsPayable(String value) {
                    this.totalAccountsPayable = value;
                }

                /**
                 * Gets the value of the creditCards property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the creditCards property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getCreditCards().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link ReportAccount }
                 * 
                 * 
                 */
                public List<ReportAccount> getCreditCards() {
                    if (creditCards == null) {
                        creditCards = new ArrayList<ReportAccount>();
                    }
                    return this.creditCards;
                }

                /**
                 * Gets the value of the totalCreditCards property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTotalCreditCards() {
                    return totalCreditCards;
                }

                /**
                 * Sets the value of the totalCreditCards property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTotalCreditCards(String value) {
                    this.totalCreditCards = value;
                }

                /**
                 * Gets the value of the otherCurrentLiabilities property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the otherCurrentLiabilities property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getOtherCurrentLiabilities().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link ReportAccount }
                 * 
                 * 
                 */
                public List<ReportAccount> getOtherCurrentLiabilities() {
                    if (otherCurrentLiabilities == null) {
                        otherCurrentLiabilities = new ArrayList<ReportAccount>();
                    }
                    return this.otherCurrentLiabilities;
                }

                /**
                 * Gets the value of the totalOtherCurrentLiabilities property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTotalOtherCurrentLiabilities() {
                    return totalOtherCurrentLiabilities;
                }

                /**
                 * Sets the value of the totalOtherCurrentLiabilities property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTotalOtherCurrentLiabilities(String value) {
                    this.totalOtherCurrentLiabilities = value;
                }

                /**
                 * Sets the value of the accountsPayable property.
                 * 
                 * @param accountsPayable
                 *     allowed object is
                 *     {@link ReportAccount }
                 *     
                 */
                public void setAccountsPayable(List<ReportAccount> accountsPayable) {
                    this.accountsPayable = accountsPayable;
                }

                /**
                 * Sets the value of the creditCards property.
                 * 
                 * @param creditCards
                 *     allowed object is
                 *     {@link ReportAccount }
                 *     
                 */
                public void setCreditCards(List<ReportAccount> creditCards) {
                    this.creditCards = creditCards;
                }

                /**
                 * Sets the value of the otherCurrentLiabilities property.
                 * 
                 * @param otherCurrentLiabilities
                 *     allowed object is
                 *     {@link ReportAccount }
                 *     
                 */
                public void setOtherCurrentLiabilities(List<ReportAccount> otherCurrentLiabilities) {
                    this.otherCurrentLiabilities = otherCurrentLiabilities;
                }

                public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
                    if (!(object instanceof QboBalanceSheetReportResponse.LiabilitiesAndEquity.Liabilities.CurrentLiabilities)) {
                        return false;
                    }
                    if (this == object) {
                        return true;
                    }
                    final QboBalanceSheetReportResponse.LiabilitiesAndEquity.Liabilities.CurrentLiabilities that = ((QboBalanceSheetReportResponse.LiabilitiesAndEquity.Liabilities.CurrentLiabilities) object);
                    {
                        List<ReportAccount> lhsAccountsPayable;
                        lhsAccountsPayable = this.getAccountsPayable();
                        List<ReportAccount> rhsAccountsPayable;
                        rhsAccountsPayable = that.getAccountsPayable();
                        if (!strategy.equals(LocatorUtils.property(thisLocator, "accountsPayable", lhsAccountsPayable), LocatorUtils.property(thatLocator, "accountsPayable", rhsAccountsPayable), lhsAccountsPayable, rhsAccountsPayable)) {
                            return false;
                        }
                    }
                    {
                        String lhsTotalAccountsPayable;
                        lhsTotalAccountsPayable = this.getTotalAccountsPayable();
                        String rhsTotalAccountsPayable;
                        rhsTotalAccountsPayable = that.getTotalAccountsPayable();
                        if (!strategy.equals(LocatorUtils.property(thisLocator, "totalAccountsPayable", lhsTotalAccountsPayable), LocatorUtils.property(thatLocator, "totalAccountsPayable", rhsTotalAccountsPayable), lhsTotalAccountsPayable, rhsTotalAccountsPayable)) {
                            return false;
                        }
                    }
                    {
                        List<ReportAccount> lhsCreditCards;
                        lhsCreditCards = this.getCreditCards();
                        List<ReportAccount> rhsCreditCards;
                        rhsCreditCards = that.getCreditCards();
                        if (!strategy.equals(LocatorUtils.property(thisLocator, "creditCards", lhsCreditCards), LocatorUtils.property(thatLocator, "creditCards", rhsCreditCards), lhsCreditCards, rhsCreditCards)) {
                            return false;
                        }
                    }
                    {
                        String lhsTotalCreditCards;
                        lhsTotalCreditCards = this.getTotalCreditCards();
                        String rhsTotalCreditCards;
                        rhsTotalCreditCards = that.getTotalCreditCards();
                        if (!strategy.equals(LocatorUtils.property(thisLocator, "totalCreditCards", lhsTotalCreditCards), LocatorUtils.property(thatLocator, "totalCreditCards", rhsTotalCreditCards), lhsTotalCreditCards, rhsTotalCreditCards)) {
                            return false;
                        }
                    }
                    {
                        List<ReportAccount> lhsOtherCurrentLiabilities;
                        lhsOtherCurrentLiabilities = this.getOtherCurrentLiabilities();
                        List<ReportAccount> rhsOtherCurrentLiabilities;
                        rhsOtherCurrentLiabilities = that.getOtherCurrentLiabilities();
                        if (!strategy.equals(LocatorUtils.property(thisLocator, "otherCurrentLiabilities", lhsOtherCurrentLiabilities), LocatorUtils.property(thatLocator, "otherCurrentLiabilities", rhsOtherCurrentLiabilities), lhsOtherCurrentLiabilities, rhsOtherCurrentLiabilities)) {
                            return false;
                        }
                    }
                    {
                        String lhsTotalOtherCurrentLiabilities;
                        lhsTotalOtherCurrentLiabilities = this.getTotalOtherCurrentLiabilities();
                        String rhsTotalOtherCurrentLiabilities;
                        rhsTotalOtherCurrentLiabilities = that.getTotalOtherCurrentLiabilities();
                        if (!strategy.equals(LocatorUtils.property(thisLocator, "totalOtherCurrentLiabilities", lhsTotalOtherCurrentLiabilities), LocatorUtils.property(thatLocator, "totalOtherCurrentLiabilities", rhsTotalOtherCurrentLiabilities), lhsTotalOtherCurrentLiabilities, rhsTotalOtherCurrentLiabilities)) {
                            return false;
                        }
                    }
                    return true;
                }

                public boolean equals(Object object) {
                    final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
                    return equals(null, null, object, strategy);
                }

                public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
                    int currentHashCode = 1;
                    {
                        List<ReportAccount> theAccountsPayable;
                        theAccountsPayable = this.getAccountsPayable();
                        currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "accountsPayable", theAccountsPayable), currentHashCode, theAccountsPayable);
                    }
                    {
                        String theTotalAccountsPayable;
                        theTotalAccountsPayable = this.getTotalAccountsPayable();
                        currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "totalAccountsPayable", theTotalAccountsPayable), currentHashCode, theTotalAccountsPayable);
                    }
                    {
                        List<ReportAccount> theCreditCards;
                        theCreditCards = this.getCreditCards();
                        currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "creditCards", theCreditCards), currentHashCode, theCreditCards);
                    }
                    {
                        String theTotalCreditCards;
                        theTotalCreditCards = this.getTotalCreditCards();
                        currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "totalCreditCards", theTotalCreditCards), currentHashCode, theTotalCreditCards);
                    }
                    {
                        List<ReportAccount> theOtherCurrentLiabilities;
                        theOtherCurrentLiabilities = this.getOtherCurrentLiabilities();
                        currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "otherCurrentLiabilities", theOtherCurrentLiabilities), currentHashCode, theOtherCurrentLiabilities);
                    }
                    {
                        String theTotalOtherCurrentLiabilities;
                        theTotalOtherCurrentLiabilities = this.getTotalOtherCurrentLiabilities();
                        currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "totalOtherCurrentLiabilities", theTotalOtherCurrentLiabilities), currentHashCode, theTotalOtherCurrentLiabilities);
                    }
                    return currentHashCode;
                }

                public int hashCode() {
                    final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
                    return this.hashCode(null, strategy);
                }

            }

        }

    }

}
