//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.2-hudson-jaxb-ri-2.2-63- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.12 at 06:01:42 PM PDT 
//


package com.intuit.sb.cdm.qbo.v2;

import java.io.Serializable;
import java.util.Calendar;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for QboCompanyReport complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QboCompanyReport">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CompanyInfo" type="{http://www.intuit.com/sb/cdm/qbo}QboCompany" minOccurs="0"/>
 *         &lt;element name="PersonInfo" type="{http://www.intuit.com/sb/cdm/v2}Person" minOccurs="0"/>
 *         &lt;element name="Trial" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="Subscription" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="SKU" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Z0NCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NoOfLogins" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="NoOfCustomers" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="MaxCustomers" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="CreationDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="SubscriptionDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="PayrollTrial" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="PayrollSubscription" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="MASUser" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QboCompanyReport", namespace = "http://www.intuit.com/sb/cdm/qbo", propOrder = {
    "companyInfo",
    "personInfo",
    "trial",
    "subscription",
    "sku",
    "z0NCode",
    "noOfLogins",
    "noOfCustomers",
    "maxCustomers",
    "creationDate",
    "subscriptionDate",
    "payrollTrial",
    "payrollSubscription",
    "masUser"
})
public class QboCompanyReport
    implements Serializable, Equals, HashCode
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "CompanyInfo")
    protected QboCompany companyInfo;
    @XmlElement(name = "PersonInfo")
    protected Person personInfo;
    @XmlElement(name = "Trial")
    protected Boolean trial;
    @XmlElement(name = "Subscription")
    protected Boolean subscription;
    @XmlElement(name = "SKU")
    protected String sku;
    @XmlElement(name = "Z0NCode")
    protected String z0NCode;
    @XmlElement(name = "NoOfLogins")
    protected Long noOfLogins;
    @XmlElement(name = "NoOfCustomers")
    protected Long noOfCustomers;
    @XmlElement(name = "MaxCustomers")
    protected Long maxCustomers;
    @XmlElement(name = "CreationDate", type = String.class)
    @XmlJavaTypeAdapter(Adapter2 .class)
    @XmlSchemaType(name = "date")
    protected Calendar creationDate;
    @XmlElement(name = "SubscriptionDate", type = String.class)
    @XmlJavaTypeAdapter(Adapter2 .class)
    @XmlSchemaType(name = "date")
    protected Calendar subscriptionDate;
    @XmlElement(name = "PayrollTrial")
    protected Boolean payrollTrial;
    @XmlElement(name = "PayrollSubscription")
    protected Boolean payrollSubscription;
    @XmlElement(name = "MASUser")
    protected Boolean masUser;

    /**
     * Gets the value of the companyInfo property.
     * 
     * @return
     *     possible object is
     *     {@link QboCompany }
     *     
     */
    public QboCompany getCompanyInfo() {
        return companyInfo;
    }

    /**
     * Sets the value of the companyInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link QboCompany }
     *     
     */
    public void setCompanyInfo(QboCompany value) {
        this.companyInfo = value;
    }

    /**
     * Gets the value of the personInfo property.
     * 
     * @return
     *     possible object is
     *     {@link Person }
     *     
     */
    public Person getPersonInfo() {
        return personInfo;
    }

    /**
     * Sets the value of the personInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Person }
     *     
     */
    public void setPersonInfo(Person value) {
        this.personInfo = value;
    }

    /**
     * Gets the value of the trial property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTrial() {
        return trial;
    }

    /**
     * Sets the value of the trial property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTrial(Boolean value) {
        this.trial = value;
    }

    /**
     * Gets the value of the subscription property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSubscription() {
        return subscription;
    }

    /**
     * Sets the value of the subscription property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSubscription(Boolean value) {
        this.subscription = value;
    }

    /**
     * Gets the value of the sku property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSKU() {
        return sku;
    }

    /**
     * Sets the value of the sku property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSKU(String value) {
        this.sku = value;
    }

    /**
     * Gets the value of the z0NCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZ0NCode() {
        return z0NCode;
    }

    /**
     * Sets the value of the z0NCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZ0NCode(String value) {
        this.z0NCode = value;
    }

    /**
     * Gets the value of the noOfLogins property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getNoOfLogins() {
        return noOfLogins;
    }

    /**
     * Sets the value of the noOfLogins property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setNoOfLogins(Long value) {
        this.noOfLogins = value;
    }

    /**
     * Gets the value of the noOfCustomers property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getNoOfCustomers() {
        return noOfCustomers;
    }

    /**
     * Sets the value of the noOfCustomers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setNoOfCustomers(Long value) {
        this.noOfCustomers = value;
    }

    /**
     * Gets the value of the maxCustomers property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getMaxCustomers() {
        return maxCustomers;
    }

    /**
     * Sets the value of the maxCustomers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMaxCustomers(Long value) {
        this.maxCustomers = value;
    }

    /**
     * Gets the value of the creationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Calendar getCreationDate() {
        return creationDate;
    }

    /**
     * Sets the value of the creationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreationDate(Calendar value) {
        this.creationDate = value;
    }

    /**
     * Gets the value of the subscriptionDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Calendar getSubscriptionDate() {
        return subscriptionDate;
    }

    /**
     * Sets the value of the subscriptionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubscriptionDate(Calendar value) {
        this.subscriptionDate = value;
    }

    /**
     * Gets the value of the payrollTrial property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPayrollTrial() {
        return payrollTrial;
    }

    /**
     * Sets the value of the payrollTrial property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPayrollTrial(Boolean value) {
        this.payrollTrial = value;
    }

    /**
     * Gets the value of the payrollSubscription property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPayrollSubscription() {
        return payrollSubscription;
    }

    /**
     * Sets the value of the payrollSubscription property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPayrollSubscription(Boolean value) {
        this.payrollSubscription = value;
    }

    /**
     * Gets the value of the masUser property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isMASUser() {
        return masUser;
    }

    /**
     * Sets the value of the masUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMASUser(Boolean value) {
        this.masUser = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof QboCompanyReport)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final QboCompanyReport that = ((QboCompanyReport) object);
        {
            QboCompany lhsCompanyInfo;
            lhsCompanyInfo = this.getCompanyInfo();
            QboCompany rhsCompanyInfo;
            rhsCompanyInfo = that.getCompanyInfo();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "companyInfo", lhsCompanyInfo), LocatorUtils.property(thatLocator, "companyInfo", rhsCompanyInfo), lhsCompanyInfo, rhsCompanyInfo)) {
                return false;
            }
        }
        {
            Person lhsPersonInfo;
            lhsPersonInfo = this.getPersonInfo();
            Person rhsPersonInfo;
            rhsPersonInfo = that.getPersonInfo();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "personInfo", lhsPersonInfo), LocatorUtils.property(thatLocator, "personInfo", rhsPersonInfo), lhsPersonInfo, rhsPersonInfo)) {
                return false;
            }
        }
        {
            Boolean lhsTrial;
            lhsTrial = this.isTrial();
            Boolean rhsTrial;
            rhsTrial = that.isTrial();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "trial", lhsTrial), LocatorUtils.property(thatLocator, "trial", rhsTrial), lhsTrial, rhsTrial)) {
                return false;
            }
        }
        {
            Boolean lhsSubscription;
            lhsSubscription = this.isSubscription();
            Boolean rhsSubscription;
            rhsSubscription = that.isSubscription();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "subscription", lhsSubscription), LocatorUtils.property(thatLocator, "subscription", rhsSubscription), lhsSubscription, rhsSubscription)) {
                return false;
            }
        }
        {
            String lhsSKU;
            lhsSKU = this.getSKU();
            String rhsSKU;
            rhsSKU = that.getSKU();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "sku", lhsSKU), LocatorUtils.property(thatLocator, "sku", rhsSKU), lhsSKU, rhsSKU)) {
                return false;
            }
        }
        {
            String lhsZ0NCode;
            lhsZ0NCode = this.getZ0NCode();
            String rhsZ0NCode;
            rhsZ0NCode = that.getZ0NCode();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "z0NCode", lhsZ0NCode), LocatorUtils.property(thatLocator, "z0NCode", rhsZ0NCode), lhsZ0NCode, rhsZ0NCode)) {
                return false;
            }
        }
        {
            Long lhsNoOfLogins;
            lhsNoOfLogins = this.getNoOfLogins();
            Long rhsNoOfLogins;
            rhsNoOfLogins = that.getNoOfLogins();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "noOfLogins", lhsNoOfLogins), LocatorUtils.property(thatLocator, "noOfLogins", rhsNoOfLogins), lhsNoOfLogins, rhsNoOfLogins)) {
                return false;
            }
        }
        {
            Long lhsNoOfCustomers;
            lhsNoOfCustomers = this.getNoOfCustomers();
            Long rhsNoOfCustomers;
            rhsNoOfCustomers = that.getNoOfCustomers();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "noOfCustomers", lhsNoOfCustomers), LocatorUtils.property(thatLocator, "noOfCustomers", rhsNoOfCustomers), lhsNoOfCustomers, rhsNoOfCustomers)) {
                return false;
            }
        }
        {
            Long lhsMaxCustomers;
            lhsMaxCustomers = this.getMaxCustomers();
            Long rhsMaxCustomers;
            rhsMaxCustomers = that.getMaxCustomers();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "maxCustomers", lhsMaxCustomers), LocatorUtils.property(thatLocator, "maxCustomers", rhsMaxCustomers), lhsMaxCustomers, rhsMaxCustomers)) {
                return false;
            }
        }
        {
            Calendar lhsCreationDate;
            lhsCreationDate = this.getCreationDate();
            Calendar rhsCreationDate;
            rhsCreationDate = that.getCreationDate();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "creationDate", lhsCreationDate), LocatorUtils.property(thatLocator, "creationDate", rhsCreationDate), lhsCreationDate, rhsCreationDate)) {
                return false;
            }
        }
        {
            Calendar lhsSubscriptionDate;
            lhsSubscriptionDate = this.getSubscriptionDate();
            Calendar rhsSubscriptionDate;
            rhsSubscriptionDate = that.getSubscriptionDate();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "subscriptionDate", lhsSubscriptionDate), LocatorUtils.property(thatLocator, "subscriptionDate", rhsSubscriptionDate), lhsSubscriptionDate, rhsSubscriptionDate)) {
                return false;
            }
        }
        {
            Boolean lhsPayrollTrial;
            lhsPayrollTrial = this.isPayrollTrial();
            Boolean rhsPayrollTrial;
            rhsPayrollTrial = that.isPayrollTrial();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "payrollTrial", lhsPayrollTrial), LocatorUtils.property(thatLocator, "payrollTrial", rhsPayrollTrial), lhsPayrollTrial, rhsPayrollTrial)) {
                return false;
            }
        }
        {
            Boolean lhsPayrollSubscription;
            lhsPayrollSubscription = this.isPayrollSubscription();
            Boolean rhsPayrollSubscription;
            rhsPayrollSubscription = that.isPayrollSubscription();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "payrollSubscription", lhsPayrollSubscription), LocatorUtils.property(thatLocator, "payrollSubscription", rhsPayrollSubscription), lhsPayrollSubscription, rhsPayrollSubscription)) {
                return false;
            }
        }
        {
            Boolean lhsMASUser;
            lhsMASUser = this.isMASUser();
            Boolean rhsMASUser;
            rhsMASUser = that.isMASUser();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "masUser", lhsMASUser), LocatorUtils.property(thatLocator, "masUser", rhsMASUser), lhsMASUser, rhsMASUser)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            QboCompany theCompanyInfo;
            theCompanyInfo = this.getCompanyInfo();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "companyInfo", theCompanyInfo), currentHashCode, theCompanyInfo);
        }
        {
            Person thePersonInfo;
            thePersonInfo = this.getPersonInfo();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "personInfo", thePersonInfo), currentHashCode, thePersonInfo);
        }
        {
            Boolean theTrial;
            theTrial = this.isTrial();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "trial", theTrial), currentHashCode, theTrial);
        }
        {
            Boolean theSubscription;
            theSubscription = this.isSubscription();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "subscription", theSubscription), currentHashCode, theSubscription);
        }
        {
            String theSKU;
            theSKU = this.getSKU();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "sku", theSKU), currentHashCode, theSKU);
        }
        {
            String theZ0NCode;
            theZ0NCode = this.getZ0NCode();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "z0NCode", theZ0NCode), currentHashCode, theZ0NCode);
        }
        {
            Long theNoOfLogins;
            theNoOfLogins = this.getNoOfLogins();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "noOfLogins", theNoOfLogins), currentHashCode, theNoOfLogins);
        }
        {
            Long theNoOfCustomers;
            theNoOfCustomers = this.getNoOfCustomers();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "noOfCustomers", theNoOfCustomers), currentHashCode, theNoOfCustomers);
        }
        {
            Long theMaxCustomers;
            theMaxCustomers = this.getMaxCustomers();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "maxCustomers", theMaxCustomers), currentHashCode, theMaxCustomers);
        }
        {
            Calendar theCreationDate;
            theCreationDate = this.getCreationDate();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "creationDate", theCreationDate), currentHashCode, theCreationDate);
        }
        {
            Calendar theSubscriptionDate;
            theSubscriptionDate = this.getSubscriptionDate();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "subscriptionDate", theSubscriptionDate), currentHashCode, theSubscriptionDate);
        }
        {
            Boolean thePayrollTrial;
            thePayrollTrial = this.isPayrollTrial();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "payrollTrial", thePayrollTrial), currentHashCode, thePayrollTrial);
        }
        {
            Boolean thePayrollSubscription;
            thePayrollSubscription = this.isPayrollSubscription();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "payrollSubscription", thePayrollSubscription), currentHashCode, thePayrollSubscription);
        }
        {
            Boolean theMASUser;
            theMASUser = this.isMASUser();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "masUser", theMASUser), currentHashCode, theMASUser);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
