//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.2-hudson-jaxb-ri-2.2-63- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.12 at 06:01:41 PM PDT 
//


package com.intuit.sb.cdm.qbo.v2;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for QboListReportsEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="QboListReportsEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="CustomerPhoneList"/>
 *     &lt;enumeration value="CustomerContactList"/>
 *     &lt;enumeration value="VendorPhoneList"/>
 *     &lt;enumeration value="VendorContactList"/>
 *     &lt;enumeration value="EmployeePhoneList"/>
 *     &lt;enumeration value="EmployeeContactList"/>
 *     &lt;enumeration value="AccountList"/>
 *     &lt;enumeration value="RecurringTemplateList"/>
 *     &lt;enumeration value="ItemPriceList"/>
 *     &lt;enumeration value="PaymentMethodList"/>
 *     &lt;enumeration value="TermsList"/>
 *     &lt;enumeration value="CompensationList"/>
 *     &lt;enumeration value="TaxList"/>
 *     &lt;enumeration value="OtherPaymentsAndDeductionsList"/>
 *     &lt;enumeration value="PayScheduleList"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "QboListReportsEnum", namespace = "http://www.intuit.com/sb/cdm/qboReports")
@XmlEnum
public enum QboListReportsEnum {

    @XmlEnumValue("CustomerPhoneList")
    CUSTOMER_PHONE_LIST("CustomerPhoneList"),
    @XmlEnumValue("CustomerContactList")
    CUSTOMER_CONTACT_LIST("CustomerContactList"),
    @XmlEnumValue("VendorPhoneList")
    VENDOR_PHONE_LIST("VendorPhoneList"),
    @XmlEnumValue("VendorContactList")
    VENDOR_CONTACT_LIST("VendorContactList"),
    @XmlEnumValue("EmployeePhoneList")
    EMPLOYEE_PHONE_LIST("EmployeePhoneList"),
    @XmlEnumValue("EmployeeContactList")
    EMPLOYEE_CONTACT_LIST("EmployeeContactList"),
    @XmlEnumValue("AccountList")
    ACCOUNT_LIST("AccountList"),
    @XmlEnumValue("RecurringTemplateList")
    RECURRING_TEMPLATE_LIST("RecurringTemplateList"),
    @XmlEnumValue("ItemPriceList")
    ITEM_PRICE_LIST("ItemPriceList"),
    @XmlEnumValue("PaymentMethodList")
    PAYMENT_METHOD_LIST("PaymentMethodList"),
    @XmlEnumValue("TermsList")
    TERMS_LIST("TermsList"),
    @XmlEnumValue("CompensationList")
    COMPENSATION_LIST("CompensationList"),
    @XmlEnumValue("TaxList")
    TAX_LIST("TaxList"),
    @XmlEnumValue("OtherPaymentsAndDeductionsList")
    OTHER_PAYMENTS_AND_DEDUCTIONS_LIST("OtherPaymentsAndDeductionsList"),
    @XmlEnumValue("PayScheduleList")
    PAY_SCHEDULE_LIST("PayScheduleList");
    private final String value;

    QboListReportsEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static QboListReportsEnum fromValue(String v) {
        for (QboListReportsEnum c: QboListReportsEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
