//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.2-hudson-jaxb-ri-2.2-63- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.12 at 06:01:41 PM PDT 
//


package com.intuit.sb.cdm.qbo.v2;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * Used to output customer phone/contact, vendor phone/contact, employee phone/contact, account list,
 *             recurring template list, item list, payment method list, terms list, compensation list, tax list,
 *             other payments and deductions list, pay schedule list.
 * 
 * <p>Java class for QboListReportResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QboListReportResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ReportTitle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ReportRow" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Column" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QboListReportResponse", namespace = "http://www.intuit.com/sb/cdm/qboReports", propOrder = {
    "reportTitle",
    "reportRow"
})
public class QboListReportResponse
    implements Serializable, Equals, HashCode
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "ReportTitle", required = true)
    protected String reportTitle;
    @XmlElement(name = "ReportRow")
    protected List<QboListReportResponse.ReportRow> reportRow;

    /**
     * Gets the value of the reportTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportTitle() {
        return reportTitle;
    }

    /**
     * Sets the value of the reportTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportTitle(String value) {
        this.reportTitle = value;
    }

    /**
     * Gets the value of the reportRow property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reportRow property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReportRow().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QboListReportResponse.ReportRow }
     * 
     * 
     */
    public List<QboListReportResponse.ReportRow> getReportRow() {
        if (reportRow == null) {
            reportRow = new ArrayList<QboListReportResponse.ReportRow>();
        }
        return this.reportRow;
    }

    /**
     * Sets the value of the reportRow property.
     * 
     * @param reportRow
     *     allowed object is
     *     {@link QboListReportResponse.ReportRow }
     *     
     */
    public void setReportRow(List<QboListReportResponse.ReportRow> reportRow) {
        this.reportRow = reportRow;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof QboListReportResponse)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final QboListReportResponse that = ((QboListReportResponse) object);
        {
            String lhsReportTitle;
            lhsReportTitle = this.getReportTitle();
            String rhsReportTitle;
            rhsReportTitle = that.getReportTitle();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "reportTitle", lhsReportTitle), LocatorUtils.property(thatLocator, "reportTitle", rhsReportTitle), lhsReportTitle, rhsReportTitle)) {
                return false;
            }
        }
        {
            List<QboListReportResponse.ReportRow> lhsReportRow;
            lhsReportRow = this.getReportRow();
            List<QboListReportResponse.ReportRow> rhsReportRow;
            rhsReportRow = that.getReportRow();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "reportRow", lhsReportRow), LocatorUtils.property(thatLocator, "reportRow", rhsReportRow), lhsReportRow, rhsReportRow)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            String theReportTitle;
            theReportTitle = this.getReportTitle();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "reportTitle", theReportTitle), currentHashCode, theReportTitle);
        }
        {
            List<QboListReportResponse.ReportRow> theReportRow;
            theReportRow = this.getReportRow();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "reportRow", theReportRow), currentHashCode, theReportRow);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Column" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "column",
        "value"
    })
    public static class ReportRow
        implements Serializable, Equals, HashCode
    {

        private final static long serialVersionUID = 1L;
        @XmlElement(name = "Column", namespace = "http://www.intuit.com/sb/cdm/qboReports", required = true)
        protected String column;
        @XmlElement(name = "Value", namespace = "http://www.intuit.com/sb/cdm/qboReports", required = true)
        protected String value;

        /**
         * Gets the value of the column property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getColumn() {
            return column;
        }

        /**
         * Sets the value of the column property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setColumn(String value) {
            this.column = value;
        }

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
            if (!(object instanceof QboListReportResponse.ReportRow)) {
                return false;
            }
            if (this == object) {
                return true;
            }
            final QboListReportResponse.ReportRow that = ((QboListReportResponse.ReportRow) object);
            {
                String lhsColumn;
                lhsColumn = this.getColumn();
                String rhsColumn;
                rhsColumn = that.getColumn();
                if (!strategy.equals(LocatorUtils.property(thisLocator, "column", lhsColumn), LocatorUtils.property(thatLocator, "column", rhsColumn), lhsColumn, rhsColumn)) {
                    return false;
                }
            }
            {
                String lhsValue;
                lhsValue = this.getValue();
                String rhsValue;
                rhsValue = that.getValue();
                if (!strategy.equals(LocatorUtils.property(thisLocator, "value", lhsValue), LocatorUtils.property(thatLocator, "value", rhsValue), lhsValue, rhsValue)) {
                    return false;
                }
            }
            return true;
        }

        public boolean equals(Object object) {
            final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
            return equals(null, null, object, strategy);
        }

        public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
            int currentHashCode = 1;
            {
                String theColumn;
                theColumn = this.getColumn();
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "column", theColumn), currentHashCode, theColumn);
            }
            {
                String theValue;
                theValue = this.getValue();
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "value", theValue), currentHashCode, theValue);
            }
            return currentHashCode;
        }

        public int hashCode() {
            final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
            return this.hashCode(null, strategy);
        }

    }

}
