//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.2-hudson-jaxb-ri-2.2-63- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.12 at 06:01:41 PM PDT 
//


package com.intuit.sb.cdm.qbo.v2;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * Used to request a list report (see enum for the types encompassed by that).
 *                 For now, no customization...but that will change.
 * 
 * <p>Java class for QboListReportRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QboListReportRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ListReport" type="{http://www.intuit.com/sb/cdm/qboReports}QboListReportsEnum"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QboListReportRequest", namespace = "http://www.intuit.com/sb/cdm/qboReports", propOrder = {
    "listReport"
})
public class QboListReportRequest
    implements Serializable, Equals, HashCode
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "ListReport", required = true)
    protected QboListReportsEnum listReport;

    /**
     * Gets the value of the listReport property.
     * 
     * @return
     *     possible object is
     *     {@link QboListReportsEnum }
     *     
     */
    public QboListReportsEnum getListReport() {
        return listReport;
    }

    /**
     * Sets the value of the listReport property.
     * 
     * @param value
     *     allowed object is
     *     {@link QboListReportsEnum }
     *     
     */
    public void setListReport(QboListReportsEnum value) {
        this.listReport = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof QboListReportRequest)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final QboListReportRequest that = ((QboListReportRequest) object);
        {
            QboListReportsEnum lhsListReport;
            lhsListReport = this.getListReport();
            QboListReportsEnum rhsListReport;
            rhsListReport = that.getListReport();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "listReport", lhsListReport), LocatorUtils.property(thatLocator, "listReport", rhsListReport), lhsListReport, rhsListReport)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            QboListReportsEnum theListReport;
            theListReport = this.getListReport();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "listReport", theListReport), currentHashCode, theListReport);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
