//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.2-hudson-jaxb-ri-2.2-63- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.12 at 06:01:42 PM PDT 
//


package com.intuit.sb.cdm.qbo.v2;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * Provides the definition that allows bulk data transfer of Sales Tax Payment Checks
 * 
 * <p>Java class for SalesTaxPaymentChecks complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SalesTaxPaymentChecks">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.intuit.com/sb/cdm/v2}CdmCollections">
 *       &lt;sequence>
 *         &lt;element name="SalesTaxPaymentCheck" type="{http://www.intuit.com/sb/cdm/v2}SalesTaxPaymentCheck" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SalesTaxPaymentChecks", propOrder = {
    "salesTaxPaymentCheck"
})
public class SalesTaxPaymentChecks
    extends CdmCollections
    implements Serializable, Equals, HashCode
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "SalesTaxPaymentCheck")
    protected List<SalesTaxPaymentCheck> salesTaxPaymentCheck;

    /**
     * Gets the value of the salesTaxPaymentCheck property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the salesTaxPaymentCheck property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSalesTaxPaymentCheck().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SalesTaxPaymentCheck }
     * 
     * 
     */
    public List<SalesTaxPaymentCheck> getSalesTaxPaymentCheck() {
        if (salesTaxPaymentCheck == null) {
            salesTaxPaymentCheck = new ArrayList<SalesTaxPaymentCheck>();
        }
        return this.salesTaxPaymentCheck;
    }

    /**
     * Sets the value of the salesTaxPaymentCheck property.
     * 
     * @param salesTaxPaymentCheck
     *     allowed object is
     *     {@link SalesTaxPaymentCheck }
     *     
     */
    public void setSalesTaxPaymentCheck(List<SalesTaxPaymentCheck> salesTaxPaymentCheck) {
        this.salesTaxPaymentCheck = salesTaxPaymentCheck;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof SalesTaxPaymentChecks)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        if (!super.equals(thisLocator, thatLocator, object, strategy)) {
            return false;
        }
        final SalesTaxPaymentChecks that = ((SalesTaxPaymentChecks) object);
        {
            List<SalesTaxPaymentCheck> lhsSalesTaxPaymentCheck;
            lhsSalesTaxPaymentCheck = this.getSalesTaxPaymentCheck();
            List<SalesTaxPaymentCheck> rhsSalesTaxPaymentCheck;
            rhsSalesTaxPaymentCheck = that.getSalesTaxPaymentCheck();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "salesTaxPaymentCheck", lhsSalesTaxPaymentCheck), LocatorUtils.property(thatLocator, "salesTaxPaymentCheck", rhsSalesTaxPaymentCheck), lhsSalesTaxPaymentCheck, rhsSalesTaxPaymentCheck)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = super.hashCode(locator, strategy);
        {
            List<SalesTaxPaymentCheck> theSalesTaxPaymentCheck;
            theSalesTaxPaymentCheck = this.getSalesTaxPaymentCheck();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "salesTaxPaymentCheck", theSalesTaxPaymentCheck), currentHashCode, theSalesTaxPaymentCheck);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
