//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.2-hudson-jaxb-ri-2.2-63- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.12 at 06:01:42 PM PDT 
//


package com.intuit.sb.cdm.qbo.v2;

import java.io.Serializable;
import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * Provides information that pertains to the entire Sales Receipt
 * 
 * <p>Java class for SalesReceiptHeader complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SalesReceiptHeader">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.intuit.com/sb/cdm/v2}HeaderSales">
 *       &lt;sequence>
 *         &lt;element name="ShipAddr" type="{http://www.intuit.com/sb/cdm/v2}PhysicalAddress" minOccurs="0"/>
 *         &lt;group ref="{http://www.intuit.com/sb/cdm/v2}ShipMethodReferenceGroup" minOccurs="0"/>
 *         &lt;group ref="{http://www.intuit.com/sb/cdm/v2}DepositToAccountReferenceGroup" minOccurs="0"/>
 *         &lt;group ref="{http://www.intuit.com/sb/cdm/v2}PaymentMethodReferenceGroup" minOccurs="0"/>
 *         &lt;element name="Detail" type="{http://www.intuit.com/sb/cdm/v2}PaymentDetail" minOccurs="0"/>
 *         &lt;group ref="{http://www.intuit.com/sb/cdm/v2}QboDiscountGroup" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SalesReceiptHeader", propOrder = {
    "shipAddr",
    "shipMethodId",
    "shipMethodName",
    "depositToAccountId",
    "depositToAccountName",
    "paymentMethodId",
    "paymentMethodName",
    "detail",
    "discountAmt",
    "discountRate",
    "discountAccountId",
    "discountAccountName",
    "discountTaxable"
})
public class SalesReceiptHeader
    extends HeaderSales
    implements Serializable, Equals, HashCode
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "ShipAddr")
    protected PhysicalAddress shipAddr;
    @XmlElement(name = "ShipMethodId")
    protected IdType shipMethodId;
    @XmlElement(name = "ShipMethodName")
    protected String shipMethodName;
    @XmlElement(name = "DepositToAccountId")
    protected IdType depositToAccountId;
    @XmlElement(name = "DepositToAccountName")
    protected String depositToAccountName;
    @XmlElement(name = "PaymentMethodId")
    protected IdType paymentMethodId;
    @XmlElement(name = "PaymentMethodName")
    protected String paymentMethodName;
    @XmlElement(name = "Detail")
    protected PaymentDetail detail;
    @XmlElement(name = "DiscountAmt")
    protected BigDecimal discountAmt;
    @XmlElement(name = "DiscountRate")
    protected BigDecimal discountRate;
    @XmlElement(name = "DiscountAccountId")
    protected IdType discountAccountId;
    @XmlElement(name = "DiscountAccountName")
    protected String discountAccountName;
    @XmlElement(name = "DiscountTaxable")
    protected Boolean discountTaxable;

    /**
     * Gets the value of the shipAddr property.
     * 
     * @return
     *     possible object is
     *     {@link PhysicalAddress }
     *     
     */
    public PhysicalAddress getShipAddr() {
        return shipAddr;
    }

    /**
     * Sets the value of the shipAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link PhysicalAddress }
     *     
     */
    public void setShipAddr(PhysicalAddress value) {
        this.shipAddr = value;
    }

    /**
     * Gets the value of the shipMethodId property.
     * 
     * @return
     *     possible object is
     *     {@link IdType }
     *     
     */
    public IdType getShipMethodId() {
        return shipMethodId;
    }

    /**
     * Sets the value of the shipMethodId property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdType }
     *     
     */
    public void setShipMethodId(IdType value) {
        this.shipMethodId = value;
    }

    /**
     * Gets the value of the shipMethodName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipMethodName() {
        return shipMethodName;
    }

    /**
     * Sets the value of the shipMethodName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipMethodName(String value) {
        this.shipMethodName = value;
    }

    /**
     * Gets the value of the depositToAccountId property.
     * 
     * @return
     *     possible object is
     *     {@link IdType }
     *     
     */
    public IdType getDepositToAccountId() {
        return depositToAccountId;
    }

    /**
     * Sets the value of the depositToAccountId property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdType }
     *     
     */
    public void setDepositToAccountId(IdType value) {
        this.depositToAccountId = value;
    }

    /**
     * Gets the value of the depositToAccountName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepositToAccountName() {
        return depositToAccountName;
    }

    /**
     * Sets the value of the depositToAccountName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepositToAccountName(String value) {
        this.depositToAccountName = value;
    }

    /**
     * Gets the value of the paymentMethodId property.
     * 
     * @return
     *     possible object is
     *     {@link IdType }
     *     
     */
    public IdType getPaymentMethodId() {
        return paymentMethodId;
    }

    /**
     * Sets the value of the paymentMethodId property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdType }
     *     
     */
    public void setPaymentMethodId(IdType value) {
        this.paymentMethodId = value;
    }

    /**
     * Gets the value of the paymentMethodName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentMethodName() {
        return paymentMethodName;
    }

    /**
     * Sets the value of the paymentMethodName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentMethodName(String value) {
        this.paymentMethodName = value;
    }

    /**
     * Gets the value of the detail property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentDetail }
     *     
     */
    public PaymentDetail getDetail() {
        return detail;
    }

    /**
     * Sets the value of the detail property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentDetail }
     *     
     */
    public void setDetail(PaymentDetail value) {
        this.detail = value;
    }

    /**
     * Gets the value of the discountAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDiscountAmt() {
        return discountAmt;
    }

    /**
     * Sets the value of the discountAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDiscountAmt(BigDecimal value) {
        this.discountAmt = value;
    }

    /**
     * Gets the value of the discountRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDiscountRate() {
        return discountRate;
    }

    /**
     * Sets the value of the discountRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDiscountRate(BigDecimal value) {
        this.discountRate = value;
    }

    /**
     * Gets the value of the discountAccountId property.
     * 
     * @return
     *     possible object is
     *     {@link IdType }
     *     
     */
    public IdType getDiscountAccountId() {
        return discountAccountId;
    }

    /**
     * Sets the value of the discountAccountId property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdType }
     *     
     */
    public void setDiscountAccountId(IdType value) {
        this.discountAccountId = value;
    }

    /**
     * Gets the value of the discountAccountName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiscountAccountName() {
        return discountAccountName;
    }

    /**
     * Sets the value of the discountAccountName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiscountAccountName(String value) {
        this.discountAccountName = value;
    }

    /**
     * Gets the value of the discountTaxable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDiscountTaxable() {
        return discountTaxable;
    }

    /**
     * Sets the value of the discountTaxable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDiscountTaxable(Boolean value) {
        this.discountTaxable = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof SalesReceiptHeader)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        if (!super.equals(thisLocator, thatLocator, object, strategy)) {
            return false;
        }
        final SalesReceiptHeader that = ((SalesReceiptHeader) object);
        {
            PhysicalAddress lhsShipAddr;
            lhsShipAddr = this.getShipAddr();
            PhysicalAddress rhsShipAddr;
            rhsShipAddr = that.getShipAddr();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "shipAddr", lhsShipAddr), LocatorUtils.property(thatLocator, "shipAddr", rhsShipAddr), lhsShipAddr, rhsShipAddr)) {
                return false;
            }
        }
        {
            IdType lhsShipMethodId;
            lhsShipMethodId = this.getShipMethodId();
            IdType rhsShipMethodId;
            rhsShipMethodId = that.getShipMethodId();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "shipMethodId", lhsShipMethodId), LocatorUtils.property(thatLocator, "shipMethodId", rhsShipMethodId), lhsShipMethodId, rhsShipMethodId)) {
                return false;
            }
        }
        {
            String lhsShipMethodName;
            lhsShipMethodName = this.getShipMethodName();
            String rhsShipMethodName;
            rhsShipMethodName = that.getShipMethodName();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "shipMethodName", lhsShipMethodName), LocatorUtils.property(thatLocator, "shipMethodName", rhsShipMethodName), lhsShipMethodName, rhsShipMethodName)) {
                return false;
            }
        }
        {
            IdType lhsDepositToAccountId;
            lhsDepositToAccountId = this.getDepositToAccountId();
            IdType rhsDepositToAccountId;
            rhsDepositToAccountId = that.getDepositToAccountId();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "depositToAccountId", lhsDepositToAccountId), LocatorUtils.property(thatLocator, "depositToAccountId", rhsDepositToAccountId), lhsDepositToAccountId, rhsDepositToAccountId)) {
                return false;
            }
        }
        {
            String lhsDepositToAccountName;
            lhsDepositToAccountName = this.getDepositToAccountName();
            String rhsDepositToAccountName;
            rhsDepositToAccountName = that.getDepositToAccountName();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "depositToAccountName", lhsDepositToAccountName), LocatorUtils.property(thatLocator, "depositToAccountName", rhsDepositToAccountName), lhsDepositToAccountName, rhsDepositToAccountName)) {
                return false;
            }
        }
        {
            IdType lhsPaymentMethodId;
            lhsPaymentMethodId = this.getPaymentMethodId();
            IdType rhsPaymentMethodId;
            rhsPaymentMethodId = that.getPaymentMethodId();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "paymentMethodId", lhsPaymentMethodId), LocatorUtils.property(thatLocator, "paymentMethodId", rhsPaymentMethodId), lhsPaymentMethodId, rhsPaymentMethodId)) {
                return false;
            }
        }
        {
            String lhsPaymentMethodName;
            lhsPaymentMethodName = this.getPaymentMethodName();
            String rhsPaymentMethodName;
            rhsPaymentMethodName = that.getPaymentMethodName();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "paymentMethodName", lhsPaymentMethodName), LocatorUtils.property(thatLocator, "paymentMethodName", rhsPaymentMethodName), lhsPaymentMethodName, rhsPaymentMethodName)) {
                return false;
            }
        }
        {
            PaymentDetail lhsDetail;
            lhsDetail = this.getDetail();
            PaymentDetail rhsDetail;
            rhsDetail = that.getDetail();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "detail", lhsDetail), LocatorUtils.property(thatLocator, "detail", rhsDetail), lhsDetail, rhsDetail)) {
                return false;
            }
        }
        {
            BigDecimal lhsDiscountAmt;
            lhsDiscountAmt = this.getDiscountAmt();
            BigDecimal rhsDiscountAmt;
            rhsDiscountAmt = that.getDiscountAmt();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "discountAmt", lhsDiscountAmt), LocatorUtils.property(thatLocator, "discountAmt", rhsDiscountAmt), lhsDiscountAmt, rhsDiscountAmt)) {
                return false;
            }
        }
        {
            BigDecimal lhsDiscountRate;
            lhsDiscountRate = this.getDiscountRate();
            BigDecimal rhsDiscountRate;
            rhsDiscountRate = that.getDiscountRate();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "discountRate", lhsDiscountRate), LocatorUtils.property(thatLocator, "discountRate", rhsDiscountRate), lhsDiscountRate, rhsDiscountRate)) {
                return false;
            }
        }
        {
            IdType lhsDiscountAccountId;
            lhsDiscountAccountId = this.getDiscountAccountId();
            IdType rhsDiscountAccountId;
            rhsDiscountAccountId = that.getDiscountAccountId();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "discountAccountId", lhsDiscountAccountId), LocatorUtils.property(thatLocator, "discountAccountId", rhsDiscountAccountId), lhsDiscountAccountId, rhsDiscountAccountId)) {
                return false;
            }
        }
        {
            String lhsDiscountAccountName;
            lhsDiscountAccountName = this.getDiscountAccountName();
            String rhsDiscountAccountName;
            rhsDiscountAccountName = that.getDiscountAccountName();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "discountAccountName", lhsDiscountAccountName), LocatorUtils.property(thatLocator, "discountAccountName", rhsDiscountAccountName), lhsDiscountAccountName, rhsDiscountAccountName)) {
                return false;
            }
        }
        {
            Boolean lhsDiscountTaxable;
            lhsDiscountTaxable = this.isDiscountTaxable();
            Boolean rhsDiscountTaxable;
            rhsDiscountTaxable = that.isDiscountTaxable();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "discountTaxable", lhsDiscountTaxable), LocatorUtils.property(thatLocator, "discountTaxable", rhsDiscountTaxable), lhsDiscountTaxable, rhsDiscountTaxable)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = super.hashCode(locator, strategy);
        {
            PhysicalAddress theShipAddr;
            theShipAddr = this.getShipAddr();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "shipAddr", theShipAddr), currentHashCode, theShipAddr);
        }
        {
            IdType theShipMethodId;
            theShipMethodId = this.getShipMethodId();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "shipMethodId", theShipMethodId), currentHashCode, theShipMethodId);
        }
        {
            String theShipMethodName;
            theShipMethodName = this.getShipMethodName();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "shipMethodName", theShipMethodName), currentHashCode, theShipMethodName);
        }
        {
            IdType theDepositToAccountId;
            theDepositToAccountId = this.getDepositToAccountId();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "depositToAccountId", theDepositToAccountId), currentHashCode, theDepositToAccountId);
        }
        {
            String theDepositToAccountName;
            theDepositToAccountName = this.getDepositToAccountName();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "depositToAccountName", theDepositToAccountName), currentHashCode, theDepositToAccountName);
        }
        {
            IdType thePaymentMethodId;
            thePaymentMethodId = this.getPaymentMethodId();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "paymentMethodId", thePaymentMethodId), currentHashCode, thePaymentMethodId);
        }
        {
            String thePaymentMethodName;
            thePaymentMethodName = this.getPaymentMethodName();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "paymentMethodName", thePaymentMethodName), currentHashCode, thePaymentMethodName);
        }
        {
            PaymentDetail theDetail;
            theDetail = this.getDetail();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "detail", theDetail), currentHashCode, theDetail);
        }
        {
            BigDecimal theDiscountAmt;
            theDiscountAmt = this.getDiscountAmt();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "discountAmt", theDiscountAmt), currentHashCode, theDiscountAmt);
        }
        {
            BigDecimal theDiscountRate;
            theDiscountRate = this.getDiscountRate();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "discountRate", theDiscountRate), currentHashCode, theDiscountRate);
        }
        {
            IdType theDiscountAccountId;
            theDiscountAccountId = this.getDiscountAccountId();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "discountAccountId", theDiscountAccountId), currentHashCode, theDiscountAccountId);
        }
        {
            String theDiscountAccountName;
            theDiscountAccountName = this.getDiscountAccountName();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "discountAccountName", theDiscountAccountName), currentHashCode, theDiscountAccountName);
        }
        {
            Boolean theDiscountTaxable;
            theDiscountTaxable = this.isDiscountTaxable();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "discountTaxable", theDiscountTaxable), currentHashCode, theDiscountTaxable);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
