//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.2-hudson-jaxb-ri-2.2-63- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.12 at 06:01:42 PM PDT 
//


package com.intuit.sb.cdm.qbo.v2;

import java.io.Serializable;
import java.util.Calendar;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 *  Describes the Party as a Vendor Role view 
 * 
 * <p>Java class for Vendor complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Vendor">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.intuit.com/sb/cdm/v2}RoleBase">
 *       &lt;sequence>
 *         &lt;element name="Active" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="ShowAs" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;group ref="{http://www.intuit.com/sb/cdm/v2}VendorTypeReferenceGroup" minOccurs="0"/>
 *         &lt;group ref="{http://www.intuit.com/sb/cdm/v2}SalesTermReferenceGroup" minOccurs="0"/>
 *         &lt;element name="OpenBalance" type="{http://www.intuit.com/sb/cdm/v2}Money" minOccurs="0"/>
 *         &lt;element name="OpenBalanceDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="CreditLimit" type="{http://www.intuit.com/sb/cdm/v2}Money" minOccurs="0"/>
 *         &lt;element name="AcctNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Vendor1099" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Vendor", propOrder = {
    "active",
    "showAs",
    "vendorTypeId",
    "vendorTypeName",
    "salesTermId",
    "salesTermName",
    "openBalance",
    "openBalanceDate",
    "creditLimit",
    "acctNum",
    "vendor1099"
})
public class Vendor
    extends RoleBase
    implements Serializable, Equals, HashCode
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "Active")
    protected Boolean active;
    @XmlElement(name = "ShowAs")
    protected String showAs;
    @XmlElement(name = "VendorTypeId")
    protected IdType vendorTypeId;
    @XmlElement(name = "VendorTypeName")
    protected String vendorTypeName;
    @XmlElement(name = "SalesTermId")
    protected IdType salesTermId;
    @XmlElement(name = "SalesTermName")
    protected String salesTermName;
    @XmlElement(name = "OpenBalance")
    protected Money openBalance;
    @XmlElement(name = "OpenBalanceDate", type = String.class)
    @XmlJavaTypeAdapter(Adapter2 .class)
    @XmlSchemaType(name = "date")
    protected Calendar openBalanceDate;
    @XmlElement(name = "CreditLimit")
    protected Money creditLimit;
    @XmlElement(name = "AcctNum")
    protected String acctNum;
    @XmlElement(name = "Vendor1099")
    protected Boolean vendor1099;

    /**
     * Gets the value of the active property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isActive() {
        return active;
    }

    /**
     * Sets the value of the active property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setActive(Boolean value) {
        this.active = value;
    }

    /**
     * Gets the value of the showAs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShowAs() {
        return showAs;
    }

    /**
     * Sets the value of the showAs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShowAs(String value) {
        this.showAs = value;
    }

    /**
     * Gets the value of the vendorTypeId property.
     * 
     * @return
     *     possible object is
     *     {@link IdType }
     *     
     */
    public IdType getVendorTypeId() {
        return vendorTypeId;
    }

    /**
     * Sets the value of the vendorTypeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdType }
     *     
     */
    public void setVendorTypeId(IdType value) {
        this.vendorTypeId = value;
    }

    /**
     * Gets the value of the vendorTypeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVendorTypeName() {
        return vendorTypeName;
    }

    /**
     * Sets the value of the vendorTypeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVendorTypeName(String value) {
        this.vendorTypeName = value;
    }

    /**
     * Gets the value of the salesTermId property.
     * 
     * @return
     *     possible object is
     *     {@link IdType }
     *     
     */
    public IdType getSalesTermId() {
        return salesTermId;
    }

    /**
     * Sets the value of the salesTermId property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdType }
     *     
     */
    public void setSalesTermId(IdType value) {
        this.salesTermId = value;
    }

    /**
     * Gets the value of the salesTermName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSalesTermName() {
        return salesTermName;
    }

    /**
     * Sets the value of the salesTermName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSalesTermName(String value) {
        this.salesTermName = value;
    }

    /**
     * Gets the value of the openBalance property.
     * 
     * @return
     *     possible object is
     *     {@link Money }
     *     
     */
    public Money getOpenBalance() {
        return openBalance;
    }

    /**
     * Sets the value of the openBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Money }
     *     
     */
    public void setOpenBalance(Money value) {
        this.openBalance = value;
    }

    /**
     * Gets the value of the openBalanceDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Calendar getOpenBalanceDate() {
        return openBalanceDate;
    }

    /**
     * Sets the value of the openBalanceDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpenBalanceDate(Calendar value) {
        this.openBalanceDate = value;
    }

    /**
     * Gets the value of the creditLimit property.
     * 
     * @return
     *     possible object is
     *     {@link Money }
     *     
     */
    public Money getCreditLimit() {
        return creditLimit;
    }

    /**
     * Sets the value of the creditLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Money }
     *     
     */
    public void setCreditLimit(Money value) {
        this.creditLimit = value;
    }

    /**
     * Gets the value of the acctNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcctNum() {
        return acctNum;
    }

    /**
     * Sets the value of the acctNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcctNum(String value) {
        this.acctNum = value;
    }

    /**
     * Gets the value of the vendor1099 property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isVendor1099() {
        return vendor1099;
    }

    /**
     * Sets the value of the vendor1099 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setVendor1099(Boolean value) {
        this.vendor1099 = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof Vendor)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        if (!super.equals(thisLocator, thatLocator, object, strategy)) {
            return false;
        }
        final Vendor that = ((Vendor) object);
        {
            Boolean lhsActive;
            lhsActive = this.isActive();
            Boolean rhsActive;
            rhsActive = that.isActive();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "active", lhsActive), LocatorUtils.property(thatLocator, "active", rhsActive), lhsActive, rhsActive)) {
                return false;
            }
        }
        {
            String lhsShowAs;
            lhsShowAs = this.getShowAs();
            String rhsShowAs;
            rhsShowAs = that.getShowAs();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "showAs", lhsShowAs), LocatorUtils.property(thatLocator, "showAs", rhsShowAs), lhsShowAs, rhsShowAs)) {
                return false;
            }
        }
        {
            IdType lhsVendorTypeId;
            lhsVendorTypeId = this.getVendorTypeId();
            IdType rhsVendorTypeId;
            rhsVendorTypeId = that.getVendorTypeId();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "vendorTypeId", lhsVendorTypeId), LocatorUtils.property(thatLocator, "vendorTypeId", rhsVendorTypeId), lhsVendorTypeId, rhsVendorTypeId)) {
                return false;
            }
        }
        {
            String lhsVendorTypeName;
            lhsVendorTypeName = this.getVendorTypeName();
            String rhsVendorTypeName;
            rhsVendorTypeName = that.getVendorTypeName();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "vendorTypeName", lhsVendorTypeName), LocatorUtils.property(thatLocator, "vendorTypeName", rhsVendorTypeName), lhsVendorTypeName, rhsVendorTypeName)) {
                return false;
            }
        }
        {
            IdType lhsSalesTermId;
            lhsSalesTermId = this.getSalesTermId();
            IdType rhsSalesTermId;
            rhsSalesTermId = that.getSalesTermId();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "salesTermId", lhsSalesTermId), LocatorUtils.property(thatLocator, "salesTermId", rhsSalesTermId), lhsSalesTermId, rhsSalesTermId)) {
                return false;
            }
        }
        {
            String lhsSalesTermName;
            lhsSalesTermName = this.getSalesTermName();
            String rhsSalesTermName;
            rhsSalesTermName = that.getSalesTermName();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "salesTermName", lhsSalesTermName), LocatorUtils.property(thatLocator, "salesTermName", rhsSalesTermName), lhsSalesTermName, rhsSalesTermName)) {
                return false;
            }
        }
        {
            Money lhsOpenBalance;
            lhsOpenBalance = this.getOpenBalance();
            Money rhsOpenBalance;
            rhsOpenBalance = that.getOpenBalance();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "openBalance", lhsOpenBalance), LocatorUtils.property(thatLocator, "openBalance", rhsOpenBalance), lhsOpenBalance, rhsOpenBalance)) {
                return false;
            }
        }
        {
            Calendar lhsOpenBalanceDate;
            lhsOpenBalanceDate = this.getOpenBalanceDate();
            Calendar rhsOpenBalanceDate;
            rhsOpenBalanceDate = that.getOpenBalanceDate();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "openBalanceDate", lhsOpenBalanceDate), LocatorUtils.property(thatLocator, "openBalanceDate", rhsOpenBalanceDate), lhsOpenBalanceDate, rhsOpenBalanceDate)) {
                return false;
            }
        }
        {
            Money lhsCreditLimit;
            lhsCreditLimit = this.getCreditLimit();
            Money rhsCreditLimit;
            rhsCreditLimit = that.getCreditLimit();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "creditLimit", lhsCreditLimit), LocatorUtils.property(thatLocator, "creditLimit", rhsCreditLimit), lhsCreditLimit, rhsCreditLimit)) {
                return false;
            }
        }
        {
            String lhsAcctNum;
            lhsAcctNum = this.getAcctNum();
            String rhsAcctNum;
            rhsAcctNum = that.getAcctNum();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "acctNum", lhsAcctNum), LocatorUtils.property(thatLocator, "acctNum", rhsAcctNum), lhsAcctNum, rhsAcctNum)) {
                return false;
            }
        }
        {
            Boolean lhsVendor1099;
            lhsVendor1099 = this.isVendor1099();
            Boolean rhsVendor1099;
            rhsVendor1099 = that.isVendor1099();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "vendor1099", lhsVendor1099), LocatorUtils.property(thatLocator, "vendor1099", rhsVendor1099), lhsVendor1099, rhsVendor1099)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = super.hashCode(locator, strategy);
        {
            Boolean theActive;
            theActive = this.isActive();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "active", theActive), currentHashCode, theActive);
        }
        {
            String theShowAs;
            theShowAs = this.getShowAs();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "showAs", theShowAs), currentHashCode, theShowAs);
        }
        {
            IdType theVendorTypeId;
            theVendorTypeId = this.getVendorTypeId();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "vendorTypeId", theVendorTypeId), currentHashCode, theVendorTypeId);
        }
        {
            String theVendorTypeName;
            theVendorTypeName = this.getVendorTypeName();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "vendorTypeName", theVendorTypeName), currentHashCode, theVendorTypeName);
        }
        {
            IdType theSalesTermId;
            theSalesTermId = this.getSalesTermId();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "salesTermId", theSalesTermId), currentHashCode, theSalesTermId);
        }
        {
            String theSalesTermName;
            theSalesTermName = this.getSalesTermName();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "salesTermName", theSalesTermName), currentHashCode, theSalesTermName);
        }
        {
            Money theOpenBalance;
            theOpenBalance = this.getOpenBalance();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "openBalance", theOpenBalance), currentHashCode, theOpenBalance);
        }
        {
            Calendar theOpenBalanceDate;
            theOpenBalanceDate = this.getOpenBalanceDate();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "openBalanceDate", theOpenBalanceDate), currentHashCode, theOpenBalanceDate);
        }
        {
            Money theCreditLimit;
            theCreditLimit = this.getCreditLimit();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "creditLimit", theCreditLimit), currentHashCode, theCreditLimit);
        }
        {
            String theAcctNum;
            theAcctNum = this.getAcctNum();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "acctNum", theAcctNum), currentHashCode, theAcctNum);
        }
        {
            Boolean theVendor1099;
            theVendor1099 = this.isVendor1099();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "vendor1099", theVendor1099), currentHashCode, theVendor1099);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
