//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.2-hudson-jaxb-ri-2.2-63- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.12 at 06:01:42 PM PDT 
//


package com.intuit.sb.cdm.qbo.v2;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for VendorRef complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VendorRef">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;group ref="{http://www.intuit.com/sb/cdm/v2}VendorReferenceGroup"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VendorRef", propOrder = {
    "vendorId",
    "vendorName"
})
public class VendorRef
    implements Serializable, Equals, HashCode
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "VendorId")
    protected IdType vendorId;
    @XmlElement(name = "VendorName")
    protected String vendorName;

    /**
     * Gets the value of the vendorId property.
     * 
     * @return
     *     possible object is
     *     {@link IdType }
     *     
     */
    public IdType getVendorId() {
        return vendorId;
    }

    /**
     * Sets the value of the vendorId property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdType }
     *     
     */
    public void setVendorId(IdType value) {
        this.vendorId = value;
    }

    /**
     * Gets the value of the vendorName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVendorName() {
        return vendorName;
    }

    /**
     * Sets the value of the vendorName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVendorName(String value) {
        this.vendorName = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof VendorRef)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final VendorRef that = ((VendorRef) object);
        {
            IdType lhsVendorId;
            lhsVendorId = this.getVendorId();
            IdType rhsVendorId;
            rhsVendorId = that.getVendorId();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "vendorId", lhsVendorId), LocatorUtils.property(thatLocator, "vendorId", rhsVendorId), lhsVendorId, rhsVendorId)) {
                return false;
            }
        }
        {
            String lhsVendorName;
            lhsVendorName = this.getVendorName();
            String rhsVendorName;
            rhsVendorName = that.getVendorName();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "vendorName", lhsVendorName), LocatorUtils.property(thatLocator, "vendorName", rhsVendorName), lhsVendorName, rhsVendorName)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            IdType theVendorId;
            theVendorId = this.getVendorId();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "vendorId", theVendorId), currentHashCode, theVendorId);
        }
        {
            String theVendorName;
            theVendorName = this.getVendorName();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "vendorName", theVendorName), currentHashCode, theVendorName);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
